package hooks

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"gopkg.in/yaml.v3"
)

const aiderWrapperMarker = "# Generated by vibe-pushover."

func installAiderNotifications(path, executable, pushoverConfig string) (bool, error) {
	if runtime.GOOS == "windows" {
		return false, errors.New("Aider notification integration currently requires macOS or Linux")
	}
	document, err := readAiderConfig(path)
	if err != nil {
		return false, err
	}
	mapping := document.Content[0]
	wrapperPath := filepath.Join(filepath.Dir(path), ".aider", "vibe-pushover-notify.sh")
	wantCommand := shellQuote(wrapperPath)
	existingCommand, hasCommand, err := yamlScalarValue(mapping, "notifications-command")
	if err != nil {
		return false, err
	}
	if hasCommand && existingCommand != wantCommand {
		return false, errors.New("refusing to replace existing Aider notifications-command; remove it before installing vibe-pushover")
	}

	notificationsChanged, err := upsertYAMLScalar(mapping, "notifications", &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: "true"})
	if err != nil {
		return false, err
	}
	commandChanged, err := upsertYAMLScalar(mapping, "notifications-command", &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: wantCommand, Style: yaml.DoubleQuotedStyle})
	if err != nil {
		return false, err
	}

	wrapper := renderAiderWrapper(executable, pushoverConfig)
	wrapperChanged, err := aiderWrapperChanged(wrapperPath, wrapper)
	if err != nil {
		return false, err
	}
	configChanged := notificationsChanged || commandChanged
	if !wrapperChanged && !configChanged {
		return false, nil
	}
	if wrapperChanged {
		if err := writeGeneratedFileMode(wrapperPath, wrapper, ".vibe-pushover-*.sh", 0o700); err != nil {
			return false, err
		}
	}
	if configChanged {
		if err := writeAiderConfig(path, document); err != nil {
			return false, err
		}
	}
	return true, nil
}

func yamlScalarValue(mapping *yaml.Node, key string) (string, bool, error) {
	return yamlScalarValueFor(mapping, key, "Aider config")
}

func yamlScalarValueFor(mapping *yaml.Node, key, context string) (string, bool, error) {
	found := -1
	for index := 0; index+1 < len(mapping.Content); index += 2 {
		if mapping.Content[index].Value != key {
			continue
		}
		if found >= 0 {
			return "", false, fmt.Errorf("%s contains duplicate %q keys", context, key)
		}
		found = index + 1
	}
	if found < 0 {
		return "", false, nil
	}
	if mapping.Content[found].Kind != yaml.ScalarNode {
		return "", false, fmt.Errorf("%s field %q must be a scalar", context, key)
	}
	return mapping.Content[found].Value, true, nil
}

func readAiderConfig(path string) (*yaml.Node, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{{Kind: yaml.MappingNode, Tag: "!!map"}}}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read Aider config: %w", err)
	}
	if len(bytes.TrimSpace(data)) == 0 {
		return &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{{Kind: yaml.MappingNode, Tag: "!!map"}}}, nil
	}
	var document yaml.Node
	if err := yaml.Unmarshal(data, &document); err != nil {
		return nil, fmt.Errorf("parse Aider config: %w", err)
	}
	if document.Kind != yaml.DocumentNode || len(document.Content) != 1 || document.Content[0].Kind != yaml.MappingNode {
		return nil, errors.New("Aider config top-level value must be a mapping")
	}
	return &document, nil
}

func upsertYAMLScalar(mapping *yaml.Node, key string, want *yaml.Node) (bool, error) {
	return upsertYAMLScalarFor(mapping, key, want, "Aider config")
}

func upsertYAMLScalarFor(mapping *yaml.Node, key string, want *yaml.Node, context string) (bool, error) {
	found := -1
	for index := 0; index+1 < len(mapping.Content); index += 2 {
		if mapping.Content[index].Value != key {
			continue
		}
		if found >= 0 {
			return false, fmt.Errorf("%s contains duplicate %q keys", context, key)
		}
		found = index + 1
	}
	if found < 0 {
		mapping.Content = append(mapping.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: key},
			want,
		)
		return true, nil
	}
	current := mapping.Content[found]
	if current.Kind == want.Kind && current.Tag == want.Tag && current.Value == want.Value {
		return false, nil
	}
	current.Kind = want.Kind
	current.Tag = want.Tag
	current.Value = want.Value
	current.Style = want.Style
	return true, nil
}

func renderAiderWrapper(executable, pushoverConfig string) []byte {
	command := hookNotifyCommand(executable, "aider", "turn-complete", pushoverConfig)
	return []byte("#!/bin/sh\n" + aiderWrapperMarker + "\nprintf '%s' '{\"message\":\"Aider is ready for input.\"}' | " + command + "\n")
}

func aiderWrapperChanged(path string, want []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return true, nil
	}
	if err != nil {
		return false, fmt.Errorf("read Aider notification script: %w", err)
	}
	if !bytes.HasPrefix(existing, []byte("#!/bin/sh\n"+aiderWrapperMarker+"\n")) {
		return false, fmt.Errorf("refusing to overwrite Aider notification script not owned by vibe-pushover: %s", path)
	}
	info, err := os.Stat(path)
	if err != nil {
		return false, fmt.Errorf("stat Aider notification script: %w", err)
	}
	return !bytes.Equal(existing, want) || info.Mode().Perm()&0o100 == 0, nil
}

func writeAiderConfig(path string, document *yaml.Node) error {
	data, err := yaml.Marshal(document)
	if err != nil {
		return fmt.Errorf("encode Aider config: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create Aider config directory: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".aider-conf-*")
	if err != nil {
		return fmt.Errorf("create temporary Aider config: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return fmt.Errorf("set Aider config permissions: %w", err)
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return fmt.Errorf("write Aider config: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close Aider config: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replace Aider config: %w", err)
	}
	return nil
}
