package hooks

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
)

const ampPluginMarker = "// Generated by vibe-pushover."

func installAmpPlugin(path, executable, pushoverConfig string) (bool, error) {
	content, err := renderAmpPlugin(executable, pushoverConfig)
	if err != nil {
		return false, err
	}
	existing, err := os.ReadFile(path)
	if err == nil {
		if bytes.Equal(existing, content) {
			return false, nil
		}
		if !bytes.HasPrefix(existing, []byte(ampPluginMarker+"\n")) {
			return false, fmt.Errorf("refusing to overwrite Amp plugin not owned by vibe-pushover: %s", path)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read Amp plugin: %w", err)
	}
	if err := writeGeneratedFile(path, content, ".vibe-pushover-*.ts"); err != nil {
		return false, err
	}
	return true, nil
}

func renderAmpPlugin(executable, pushoverConfig string) ([]byte, error) {
	binaryJSON, err := json.Marshal(executable)
	if err != nil {
		return nil, fmt.Errorf("encode executable path: %w", err)
	}
	configJSON, err := json.Marshal(pushoverConfig)
	if err != nil {
		return nil, fmt.Errorf("encode config path: %w", err)
	}
	content := fmt.Sprintf(`%s
import type { PluginAPI, ThreadMessage } from "@ampcode/plugin";
import { spawn } from "node:child_process";

const binary = %s;
const configPath = %s;

function assistantText(messages: ThreadMessage[]) {
  for (let index = messages.length - 1; index >= 0; index--) {
    const message = messages[index];
    if (message?.role !== "assistant" || !Array.isArray(message.content)) continue;
    const text = message.content
      .filter((part) => part?.type === "text" && typeof part.text === "string")
      .map((part) => part.text)
      .join("");
    if (text.trim()) return text;
  }
  return "";
}

function send(eventName: string, payload: Record<string, unknown>) {
  const args = ["notify", "--agent", "amp", "--event", eventName, "--ignore-errors"];
  if (configPath) args.push("--config", configPath);
  const child = spawn(binary, args, { detached: true, stdio: ["pipe", "ignore", "inherit"] });
  child.on("error", (error) => console.error("[vibe-pushover] failed to start notifier:", error.message));
  child.stdin.on("error", (error) => console.error("[vibe-pushover] failed to send hook payload:", error.message));
  child.stdin.end(JSON.stringify(payload));
  child.unref();
}

export default function (amp: PluginAPI) {
  const cwd = amp.system.workspaceRoot
    ? amp.helpers.filePathFromURI(amp.system.workspaceRoot)
    : process.cwd();
  const subscriptions = new Map<string, { unsubscribe(): void }>();

  amp.on("agent.start", (event, ctx) => {
    subscriptions.get(event.thread.id)?.unsubscribe();
    let previousState = "";
    const subscription = ctx.thread.state.subscribe((state) => {
      if (state === "awaiting-approval" && previousState !== state) {
        send("approval-required", { cwd, message: "Amp is waiting for tool approval." });
      }
      previousState = state;
    });
    subscriptions.set(event.thread.id, subscription);
  });

  amp.on("agent.end", (event) => {
    subscriptions.get(event.thread.id)?.unsubscribe();
    subscriptions.delete(event.thread.id);
    if (event.status === "done") {
      send("turn-complete", {
        cwd,
        last_assistant_message: assistantText(event.messages),
      });
    } else if (event.status === "error") {
      send("attention-required", { cwd, message: "Amp turn ended with an error." });
    }
  });
}
`, ampPluginMarker, binaryJSON, configJSON)
	return []byte(content), nil
}
