package hooks

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

const auggieWrapperMarker = "# Generated by vibe-pushover."

func installAuggieHooks(path, executable, pushoverConfig string) (bool, error) {
	root, err := readRoot(path)
	if err != nil {
		return false, err
	}
	hooksValue, ok := root["hooks"]
	if !ok {
		hooksValue = map[string]any{}
		root["hooks"] = hooksValue
	}
	hookMap, ok := hooksValue.(map[string]any)
	if !ok {
		return false, errors.New("Auggie settings field \"hooks\" must be an object")
	}

	wrapperPath := filepath.Join(filepath.Dir(path), "hooks", "vibe-pushover.sh")
	wrapper := renderAuggieWrapper(executable, pushoverConfig)
	wrapperChanged, err := generatedExecutableChanged(wrapperPath, wrapper)
	if err != nil {
		return false, err
	}
	want := map[string]any{
		"hooks": []any{map[string]any{
			"type":    "command",
			"command": shellQuote(wrapperPath),
			"timeout": 10000,
		}},
		"metadata": map[string]any{"includeConversationData": true},
	}
	updated, hooksChanged, err := upsertAuggieHook(hookMap["Stop"], wrapperPath, want)
	if err != nil {
		return false, err
	}
	if !wrapperChanged && !hooksChanged {
		return false, nil
	}
	if wrapperChanged {
		if err := writeGeneratedFileMode(wrapperPath, wrapper, ".vibe-pushover-*.sh", 0o700); err != nil {
			return false, err
		}
	}
	if hooksChanged {
		hookMap["Stop"] = updated
		if err := writeJSON(path, root); err != nil {
			return false, err
		}
	}
	return true, nil
}

func renderAuggieWrapper(executable, pushoverConfig string) []byte {
	command := hookNotifyCommand(executable, "auggie", "turn-complete", pushoverConfig)
	command = addCommandFlag(command, "--skip-non-completion")
	return []byte("#!/bin/sh\n" + auggieWrapperMarker + "\nexec " + command + "\n")
}

func addCommandFlag(command, flag string) string {
	const before = " --ignore-errors"
	if index := bytes.Index([]byte(command), []byte(before)); index >= 0 {
		return command[:index] + " " + flag + command[index:]
	}
	return command + " " + flag
}

func generatedExecutableChanged(path string, want []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return true, nil
	}
	if err != nil {
		return false, fmt.Errorf("read generated hook script: %w", err)
	}
	wantPrefix := []byte("#!/bin/sh\n" + auggieWrapperMarker + "\n")
	if !bytes.HasPrefix(existing, wantPrefix) {
		return false, fmt.Errorf("refusing to overwrite Auggie hook script not owned by vibe-pushover: %s", path)
	}
	info, err := os.Stat(path)
	if err != nil {
		return false, fmt.Errorf("stat generated hook script: %w", err)
	}
	return !bytes.Equal(existing, want) || info.Mode().Perm()&0o100 == 0, nil
}

func upsertAuggieHook(value any, wrapperPath string, want map[string]any) ([]any, bool, error) {
	var entries []any
	if value != nil {
		var ok bool
		entries, ok = value.([]any)
		if !ok {
			return nil, false, errors.New("Auggie Stop hook value must be an array")
		}
	}
	wantCommand := shellQuote(wrapperPath)
	for index, raw := range entries {
		group, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		commands, ok := group["hooks"].([]any)
		if !ok || len(commands) == 0 {
			continue
		}
		for commandIndex, rawCommand := range commands {
			command, ok := rawCommand.(map[string]any)
			if !ok || (command["command"] != wrapperPath && command["command"] != wantCommand) {
				continue
			}
			metadataValue, hasMetadata := group["metadata"]
			metadata, ok := metadataValue.(map[string]any)
			if hasMetadata && !ok {
				return nil, false, errors.New("Auggie Stop hook metadata must be an object")
			}
			if metadata == nil {
				metadata = map[string]any{}
			}
			changed := command["type"] != "command" || command["command"] != wantCommand || fmt.Sprint(command["timeout"]) != "10000" || metadata["includeConversationData"] != true
			if !changed {
				return entries, false, nil
			}
			command["type"] = "command"
			command["command"] = wantCommand
			command["timeout"] = 10000
			metadata["includeConversationData"] = true
			commands[commandIndex] = command
			group["hooks"] = commands
			group["metadata"] = metadata
			entries[index] = group
			return entries, true, nil
		}
	}
	return append(entries, want), true, nil
}
