package hooks

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

const clineHookMarker = "# Generated by vibe-pushover for Cline."

type clinePathCommand func(name string, args ...string) (string, error)

func defaultClinePaths() ([]string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("find home directory: %w", err)
	}
	clineDir := os.Getenv("CLINE_DIR")
	if clineDir != "" {
		clineDir, err = expandHome(clineDir)
		if err != nil {
			return nil, fmt.Errorf("resolve Cline directory: %w", err)
		}
	}
	return clineDefaultPaths(runtime.GOOS, home, clineDir, func(name string, args ...string) (string, error) {
		output, err := exec.Command(name, args...).Output()
		return string(output), err
	}), nil
}

func clineDefaultPaths(goos, home, clineDir string, run clinePathCommand) []string {
	fallbackDocuments := filepath.Join(home, "Documents")
	documents := fallbackDocuments
	var output string
	var err error
	switch goos {
	case "windows":
		output, err = run("powershell", "-NoProfile", "-Command", "[System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::MyDocuments)")
	case "linux":
		output, err = run("xdg-user-dir", "DOCUMENTS")
	}
	if candidate := strings.TrimSpace(output); err == nil && isAbsolutePathForOS(goos, candidate) {
		documents = candidate
	}
	fileName := "TaskComplete"
	if goos == "windows" {
		fileName += ".ps1"
	}
	paths := []string{filepath.Join(documents, "Cline", "Hooks", fileName)}
	sameDocuments := filepath.Clean(documents) == filepath.Clean(fallbackDocuments)
	if goos == "windows" {
		sameDocuments = strings.EqualFold(filepath.Clean(documents), filepath.Clean(fallbackDocuments))
	}
	if !sameDocuments {
		if clineDir == "" {
			clineDir = filepath.Join(home, ".cline")
		}
		paths = append(paths, filepath.Join(clineDir, "hooks", fileName))
	}
	return paths
}

func installClineHook(path, executable, pushoverConfig string) (bool, error) {
	resolvedPath, err := resolveClineHookPath(path)
	if err != nil {
		return false, err
	}
	path = resolvedPath
	want := clineHookScriptForOS(runtime.GOOS, executable, pushoverConfig)
	if err := validateClineHookOwnership(path); err != nil {
		return false, err
	}
	existing, err := os.ReadFile(path)
	if err == nil {
		info, statErr := os.Stat(path)
		if statErr != nil {
			return false, fmt.Errorf("stat Cline hook: %w", statErr)
		}
		needsExecutable := runtime.GOOS != "windows" && info.Mode().Perm()&0o100 == 0
		if bytes.Equal(existing, want) && !needsExecutable {
			return false, nil
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read Cline hook: %w", err)
	}
	mode := os.FileMode(0o700)
	if runtime.GOOS == "windows" {
		mode = 0o600
	}
	if err := writeGeneratedFileMode(path, want, ".vibe-pushover-cline-*", mode); err != nil {
		return false, err
	}
	return true, nil
}

func resolveClineHookPath(path string) (string, error) {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return path, nil
	}
	if err != nil {
		return "", fmt.Errorf("inspect Cline hook: %w", err)
	}
	if info.Mode()&os.ModeSymlink == 0 {
		return path, nil
	}
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil {
		return "", fmt.Errorf("resolve Cline hook symlink: %w", err)
	}
	return resolved, nil
}

func validateClineHookOwnership(path string) error {
	existing, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read Cline hook: %w", err)
	}
	unixPrefix := []byte("#!/bin/sh\n" + clineHookMarker + "\n")
	windowsPrefix := []byte(clineHookMarker + "\n")
	if !bytes.HasPrefix(existing, unixPrefix) && !bytes.HasPrefix(existing, windowsPrefix) {
		return fmt.Errorf("refusing to overwrite Cline hook not owned by vibe-pushover: %s", path)
	}
	return nil
}

func clineHookScriptForOS(goos, executable, pushoverConfig string) []byte {
	if goos == "windows" {
		command := "& " + powerShellQuote(executable) + " notify --agent cline --event turn-complete --ignore-errors"
		command += " --skip-cline-subagent"
		if pushoverConfig != "" {
			command += " --config " + powerShellQuote(pushoverConfig)
		}
		return []byte(clineHookMarker + "\n" +
			"$payload = [Console]::In.ReadToEnd()\n" +
			"$OutputEncoding = New-Object System.Text.UTF8Encoding $false\n" +
			"$payload | " + command + " | Out-Null\n" +
			"Write-Output '{\"cancel\":false,\"contextModification\":\"\",\"errorMessage\":\"\"}'\n" +
			"exit 0\n")
	}
	command := shellQuote(executable) + " notify --agent cline --event turn-complete --ignore-errors"
	command += " --skip-cline-subagent"
	if pushoverConfig != "" {
		command += " --config " + shellQuote(pushoverConfig)
	}
	return []byte("#!/bin/sh\n" + clineHookMarker + "\n" +
		command + " >/dev/null\n" +
		"printf '%s\\n' '{\"cancel\":false,\"contextModification\":\"\",\"errorMessage\":\"\"}'\n")
}

func powerShellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}
