package hooks

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pelletier/go-toml/v2"
	"github.com/pelletier/go-toml/v2/unstable"
)

const gptmePluginMarker = "# Generated by vibe-pushover."

type gptmePluginsConfig struct {
	Paths   []string `toml:"paths"`
	Enabled []string `toml:"enabled"`
}

type gptmeConfig struct {
	Plugins gptmePluginsConfig `toml:"plugins"`
}

type gptmeConfigLayout struct {
	representation string
	blockEnd       int
	inlineStart    int
	inlineEnd      int
	pathsStart     int
	pathsEnd       int
	pathsFound     bool
	enabledStart   int
	enabledEnd     int
	enabledFound   bool
}

type gptmeReplacement struct {
	start int
	end   int
	value string
}

func installGptmePlugin(path, executable, pushoverConfig string) (bool, error) {
	pluginRoot, err := filepath.Abs(filepath.Join(filepath.Dir(path), "plugins"))
	if err != nil {
		return false, fmt.Errorf("resolve gptme plugin directory: %w", err)
	}
	pluginDir := filepath.Join(pluginRoot, "vibe_pushover")
	files := []struct {
		path    string
		content []byte
	}{
		{
			path: filepath.Join(pluginDir, "__init__.py"),
			content: []byte(gptmePluginMarker + `
"""Pushover notifications installed by vibe-pushover."""
`),
		},
		{
			path:    filepath.Join(pluginDir, "hooks", "notify.py"),
			content: renderGptmeHook(executable, pushoverConfig),
		},
	}

	fileChanged := make([]bool, len(files))
	for i, file := range files {
		fileChanged[i], err = generatedGptmeFileChanged(file.path, file.content)
		if err != nil {
			return false, err
		}
	}

	writePath, err := resolveGptmeConfigPath(path)
	if err != nil {
		return false, err
	}
	configData, err := os.ReadFile(writePath)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read gptme config: %w", err)
	}
	updatedConfig, configChanged, err := mergeGptmePluginConfig(string(configData), pluginRoot)
	if err != nil {
		return false, err
	}

	changed := configChanged
	for i, file := range files {
		if !fileChanged[i] {
			continue
		}
		if err := writeGeneratedFile(file.path, file.content, ".vibe-pushover-*.py"); err != nil {
			return false, fmt.Errorf("write gptme plugin: %w", err)
		}
		changed = true
	}
	if configChanged {
		if err := writeGeneratedFile(writePath, []byte(updatedConfig), ".vibe-pushover-*.toml"); err != nil {
			return false, fmt.Errorf("write gptme config: %w", err)
		}
	}
	return changed, nil
}

func generatedGptmeFileChanged(path string, expected []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return true, nil
	}
	if err != nil {
		return false, fmt.Errorf("read gptme plugin: %w", err)
	}
	if bytes.Equal(existing, expected) {
		return false, nil
	}
	if !bytes.HasPrefix(existing, []byte(gptmePluginMarker)) {
		return false, fmt.Errorf("refusing to overwrite gptme plugin not owned by vibe-pushover: %s", path)
	}
	return true, nil
}

func resolveGptmeConfigPath(path string) (string, error) {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return path, nil
	}
	if err != nil {
		return "", fmt.Errorf("inspect gptme config: %w", err)
	}
	if info.Mode()&os.ModeSymlink == 0 {
		return path, nil
	}
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil {
		return "", fmt.Errorf("resolve gptme config symlink: %w", err)
	}
	return resolved, nil
}

func mergeGptmePluginConfig(content, pluginRoot string) (string, bool, error) {
	var config gptmeConfig
	if strings.TrimSpace(content) != "" {
		if err := toml.Unmarshal([]byte(content), &config); err != nil {
			return "", false, fmt.Errorf("parse gptme config: %w", err)
		}
	}
	layout, err := inspectGptmeConfigLayout([]byte(content))
	if err != nil {
		return "", false, err
	}

	paths := appendUniqueString(config.Plugins.Paths, pluginRoot)

	if layout.representation == "" {
		block := "[plugins]\npaths = " + renderTOMLStringArray(paths) + "\n"
		updated := content
		if updated != "" && !strings.HasSuffix(updated, "\n") {
			updated += "\n"
		}
		if updated != "" && !strings.HasSuffix(updated, "\n\n") {
			updated += "\n"
		}
		updated += block
		return validateGptmeConfigUpdate(content, updated)
	}

	if layout.representation == "inline" {
		inline := content[layout.inlineStart:layout.inlineEnd]
		inlineReplacements := make([]gptmeReplacement, 0, 2)
		if layout.pathsFound && !containsString(config.Plugins.Paths, pluginRoot) {
			inlineReplacements = append(inlineReplacements, gptmeReplacement{
				start: layout.pathsStart - layout.inlineStart,
				end:   layout.pathsEnd - layout.inlineStart,
				value: appendTOMLArrayValue(content[layout.pathsStart:layout.pathsEnd], pluginRoot),
			})
		}
		if layout.enabledFound && len(config.Plugins.Enabled) > 0 && !containsString(config.Plugins.Enabled, "vibe_pushover") {
			inlineReplacements = append(inlineReplacements, gptmeReplacement{
				start: layout.enabledStart - layout.inlineStart,
				end:   layout.enabledEnd - layout.inlineStart,
				value: appendTOMLArrayValue(content[layout.enabledStart:layout.enabledEnd], "vibe_pushover"),
			})
		}
		sort.Slice(inlineReplacements, func(i, j int) bool { return inlineReplacements[i].start > inlineReplacements[j].start })
		for _, replacement := range inlineReplacements {
			inline = inline[:replacement.start] + replacement.value + inline[replacement.end:]
		}
		if !layout.pathsFound {
			inline = appendTOMLInlineTableField(inline, "paths", renderTOMLStringArray(paths))
		}
		if inline == content[layout.inlineStart:layout.inlineEnd] {
			return content, false, nil
		}
		updated := content[:layout.inlineStart] + inline + content[layout.inlineEnd:]
		return validateGptmeConfigUpdate(content, updated)
	}

	replacements := make([]gptmeReplacement, 0, 2)
	if layout.pathsFound {
		if !containsString(config.Plugins.Paths, pluginRoot) {
			replacements = append(replacements, gptmeReplacement{
				start: layout.pathsStart,
				end:   layout.pathsEnd,
				value: appendTOMLArrayValue(content[layout.pathsStart:layout.pathsEnd], pluginRoot),
			})
		}
	} else {
		prefix := ""
		if layout.blockEnd > 0 && content[layout.blockEnd-1] != '\n' {
			prefix = "\n"
		}
		key := "paths"
		if layout.representation == "dotted" {
			key = "plugins.paths"
		}
		replacements = append(replacements, gptmeReplacement{
			start: layout.blockEnd,
			end:   layout.blockEnd,
			value: prefix + key + " = " + renderTOMLStringArray(paths) + "\n",
		})
	}
	if layout.enabledFound && len(config.Plugins.Enabled) > 0 && !containsString(config.Plugins.Enabled, "vibe_pushover") {
		replacements = append(replacements, gptmeReplacement{
			start: layout.enabledStart,
			end:   layout.enabledEnd,
			value: appendTOMLArrayValue(content[layout.enabledStart:layout.enabledEnd], "vibe_pushover"),
		})
	}

	sort.Slice(replacements, func(i, j int) bool { return replacements[i].start > replacements[j].start })
	updated := content
	for _, replacement := range replacements {
		updated = updated[:replacement.start] + replacement.value + updated[replacement.end:]
	}
	return validateGptmeConfigUpdate(content, updated)
}

func inspectGptmeConfigLayout(data []byte) (gptmeConfigLayout, error) {
	layout := gptmeConfigLayout{blockEnd: len(data)}
	parser := unstable.Parser{}
	parser.Reset(data)
	inPlugins := false
	rootScope := true
	for parser.NextExpression() {
		expression := parser.Expression()
		switch expression.Kind {
		case unstable.Table, unstable.ArrayTable:
			if rootScope && layout.representation == "dotted" && layout.blockEnd == len(data) {
				key := expression.Key()
				if key.Next() {
					layout.blockEnd = lineStartOffset(data, int(key.Node().Raw.Offset))
				}
			}
			rootScope = false
			if inPlugins && layout.blockEnd == len(data) {
				key := expression.Key()
				if key.Next() {
					layout.blockEnd = lineStartOffset(data, int(key.Node().Raw.Offset))
				}
			}
			inPlugins = expression.Kind == unstable.Table && expressionHasSimpleKey(expression, "plugins")
			if inPlugins {
				layout.representation = "table"
				layout.blockEnd = len(data)
			}
		case unstable.KeyValue:
			if inPlugins {
				if err := recordGptmePluginArray(data, expression, &layout); err != nil {
					return gptmeConfigLayout{}, err
				}
				continue
			}
			if !rootScope {
				continue
			}
			parts := expressionKeyParts(expression)
			if len(parts) == 2 && parts[0] == "plugins" && (parts[1] == "paths" || parts[1] == "enabled") {
				layout.representation = "dotted"
				if err := recordGptmePluginArray(data, expression, &layout); err != nil {
					return gptmeConfigLayout{}, err
				}
				continue
			}
			if len(parts) == 1 && parts[0] == "plugins" && expression.Value().Kind == unstable.InlineTable {
				layout.representation = "inline"
				start, close, err := tomlDelimitedBounds(data, int(expression.Value().Raw.Offset), '{', '}')
				if err != nil {
					return gptmeConfigLayout{}, fmt.Errorf("locate gptme inline plugin table: %w", err)
				}
				layout.inlineStart, layout.inlineEnd = start, close+1
				children := expression.Value().Children()
				for children.Next() {
					child := children.Node()
					if child.Kind == unstable.KeyValue {
						if err := recordGptmePluginArray(data, child, &layout); err != nil {
							return gptmeConfigLayout{}, err
						}
					}
				}
			}
		}
	}
	if err := parser.Error(); err != nil {
		return gptmeConfigLayout{}, fmt.Errorf("parse gptme config syntax: %w", err)
	}
	return layout, nil
}

func recordGptmePluginArray(data []byte, expression *unstable.Node, layout *gptmeConfigLayout) error {
	parts := expressionKeyParts(expression)
	name := ""
	if len(parts) == 1 {
		name = parts[0]
	} else if len(parts) == 2 && parts[0] == "plugins" {
		name = parts[1]
	}
	if (name != "paths" && name != "enabled") || expression.Value().Kind != unstable.Array {
		return nil
	}
	keys := expression.Key()
	var lastKey *unstable.Node
	for keys.Next() {
		lastKey = keys.Node()
	}
	if lastKey == nil {
		return nil
	}
	start, close, err := inlineHooksArrayDelimiters(data, int(lastKey.Raw.Offset+lastKey.Raw.Length))
	if err != nil {
		return fmt.Errorf("locate gptme plugin array: %w", err)
	}
	if name == "paths" {
		layout.pathsFound = true
		layout.pathsStart, layout.pathsEnd = start, close+1
	} else {
		layout.enabledFound = true
		layout.enabledStart, layout.enabledEnd = start, close+1
	}
	return nil
}

func expressionKeyParts(expression *unstable.Node) []string {
	keys := expression.Key()
	var parts []string
	for keys.Next() {
		parts = append(parts, string(keys.Node().Data))
	}
	return parts
}

func lineStartOffset(data []byte, offset int) int {
	for offset > 0 && data[offset-1] != '\n' {
		offset--
	}
	return offset
}

func expressionHasSimpleKey(expression *unstable.Node, want string) bool {
	keys := expression.Key()
	return keys.Next() && string(keys.Node().Data) == want && keys.Node().Next() == nil
}

func appendUniqueString(values []string, value string) []string {
	result := append([]string(nil), values...)
	for _, existing := range result {
		if existing == value {
			return result
		}
	}
	return append(result, value)
}

func containsString(values []string, value string) bool {
	for _, existing := range values {
		if existing == value {
			return true
		}
	}
	return false
}

func appendTOMLArrayValue(array, value string) string {
	if len(array) < 2 || array[0] != '[' || array[len(array)-1] != ']' {
		return array
	}
	open, close := 0, len(array)-1
	last := lastTOMLArrayToken(array, open, close)
	if last < 0 {
		return array[:open+1] + tomlString(value) + array[close:]
	}
	if array[last] != ',' {
		array = array[:last+1] + "," + array[last+1:]
		close++
	}
	if strings.Contains(array[open+1:close], "\n") {
		lineStart := lineStartOffset([]byte(array), close)
		closingIndent := array[lineStart:close]
		return array[:lineStart] + closingIndent + "  " + tomlString(value) + ",\n" + array[lineStart:]
	}
	return array[:close] + " " + tomlString(value) + array[close:]
}

func appendTOMLInlineTableField(table, key, value string) string {
	if len(table) < 2 || table[0] != '{' || table[len(table)-1] != '}' {
		return table
	}
	open, close := 0, len(table)-1
	last := lastTOMLArrayToken(table, open, close)
	if last < 0 {
		return table[:open+1] + " " + key + " = " + value + " " + table[close:]
	}
	if table[last] != ',' {
		table = table[:last+1] + "," + table[last+1:]
		close++
	}
	if strings.Contains(table[open+1:close], "\n") {
		lineStart := lineStartOffset([]byte(table), close)
		closingIndent := table[lineStart:close]
		return table[:lineStart] + closingIndent + "  " + key + " = " + value + ",\n" + table[lineStart:]
	}
	return table[:close] + " " + key + " = " + value + table[close:]
}

func tomlDelimitedBounds(data []byte, offset int, open, close byte) (int, int, error) {
	for offset < len(data) && data[offset] != open && data[offset] != '\n' {
		offset++
	}
	if offset >= len(data) || data[offset] != open {
		return 0, 0, fmt.Errorf("expected %q delimiter", open)
	}
	start := offset
	depth := 0
	var quote byte
	triple := false
	inComment := false
	for i := offset; i < len(data); i++ {
		c := data[i]
		if inComment {
			if c == '\n' {
				inComment = false
			}
			continue
		}
		if quote != 0 {
			if quote == '"' && c == '\\' && !triple {
				i++
				continue
			}
			if triple {
				if i+2 < len(data) && c == quote && data[i+1] == quote && data[i+2] == quote {
					i += 2
					quote = 0
					triple = false
				}
			} else if c == quote {
				quote = 0
			}
			continue
		}
		switch c {
		case '#':
			inComment = true
		case '"', '\'':
			quote = c
			triple = i+2 < len(data) && data[i+1] == c && data[i+2] == c
			if triple {
				i += 2
			}
		case open:
			depth++
		case close:
			depth--
			if depth == 0 {
				return start, i, nil
			}
		}
	}
	return 0, 0, fmt.Errorf("unterminated %q delimiter", open)
}

func lastTOMLArrayToken(array string, open, close int) int {
	last := -1
	inComment := false
	var quote byte
	triple := false
	for i := open + 1; i < close; i++ {
		c := array[i]
		if inComment {
			if c == '\n' {
				inComment = false
			}
			continue
		}
		if quote != 0 {
			if quote == '"' && c == '\\' && !triple {
				i++
				continue
			}
			if triple {
				if i+2 < close && c == quote && array[i+1] == quote && array[i+2] == quote {
					last = i + 2
					i += 2
					quote = 0
					triple = false
				}
			} else if c == quote {
				last = i
				quote = 0
			}
			continue
		}
		switch c {
		case '#':
			inComment = true
		case '"', '\'':
			quote = c
			triple = i+2 < close && array[i+1] == c && array[i+2] == c
			last = i
			if triple {
				i += 2
			}
		case ' ', '\t', '\r', '\n':
		default:
			last = i
		}
	}
	return last
}

func renderTOMLStringArray(values []string) string {
	encoded := make([]string, len(values))
	for i, value := range values {
		encoded[i] = tomlString(value)
	}
	return "[" + strings.Join(encoded, ", ") + "]"
}

func validateGptmeConfigUpdate(original, updated string) (string, bool, error) {
	if updated == original {
		return original, false, nil
	}
	var config gptmeConfig
	if err := toml.Unmarshal([]byte(updated), &config); err != nil {
		return "", false, fmt.Errorf("generated gptme config is invalid: %w", err)
	}
	return updated, true, nil
}

func renderGptmeHook(executable, pushoverConfig string) []byte {
	return []byte(fmt.Sprintf(`%s
"""Native gptme lifecycle notifications installed by vibe-pushover."""

import json
import os
import subprocess
from pathlib import Path

from gptme.hooks import HookType, get_hooks, register_hook
from gptme.hooks.confirm import is_auto_confirm_active

BINARY = %s
CONFIG_PATH = %s
APPROVAL_HOOK_NAME = "vibe_pushover_approval"


def _notify(event, payload):
    args = [BINARY, "notify", "--agent", "gptme", "--event", event, "--ignore-errors"]
    if CONFIG_PATH:
        args.extend(["--config", CONFIG_PATH])
    try:
        process = subprocess.Popen(
            args,
            stdin=subprocess.PIPE,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            close_fds=True,
        )
        if process.stdin is not None:
            process.stdin.write(json.dumps(payload, ensure_ascii=False).encode("utf-8"))
            process.stdin.close()
    except (OSError, ValueError, BrokenPipeError):
        pass


def _compact_line(value):
    for line in str(value or "").splitlines():
        compact = " ".join(line.split())
        if compact:
            return compact[:800]
    return ""


def _last_assistant_message(manager):
    for message in reversed(manager.log.messages):
        if message.role == "assistant" and not message.hide:
            compact = _compact_line(message.content)
            if compact:
                return compact
    return ""


def notify_turn_post(manager):
    if os.environ.get("GPTME_SUBAGENT_AGENT_ID"):
        return
    _notify(
        "turn-complete",
        {
            "cwd": str(manager.workspace),
            "session_id": manager.chat_id,
            "last_assistant_message": _last_assistant_message(manager),
        },
    )


def _notify_tool_confirm(tool_use, preview=None, workspace=None):
    enabled_hooks = [hook for hook in get_hooks(HookType.TOOL_CONFIRM) if hook.enabled]
    observer_index = next(
        (index for index, hook in enumerate(enabled_hooks) if hook.name == APPROVAL_HOOK_NAME),
        -1,
    )
    if observer_index < 0:
        return None
    next_hooks = enabled_hooks[observer_index + 1 :]
    if not next_hooks or next_hooks[0].name != "cli_confirm":
        return None
    if is_auto_confirm_active():
        return None

    detail = _compact_line(preview or getattr(tool_use, "content", ""))
    _notify(
        "approval-required",
        {
            "cwd": str(workspace or Path.cwd()),
            "tool_name": str(getattr(tool_use, "tool", "Tool")),
            "message": detail or "Tool execution requires approval.",
        },
    )
    return None


def notify_tool_confirm(tool_use, preview=None, workspace=None):
    try:
        return _notify_tool_confirm(tool_use, preview, workspace)
    except Exception:
        # A notification observer must never affect gptme's approval decision.
        return None


def register():
    register_hook(
        name="vibe_pushover_turn_post",
        hook_type=HookType.TURN_POST,
        func=notify_turn_post,
        async_mode=True,
    )
    register_hook(
        name=APPROVAL_HOOK_NAME,
        hook_type=HookType.TOOL_CONFIRM,
        func=notify_tool_confirm,
        priority=1,
    )
`, gptmePluginMarker, tomlString(executable), tomlString(pushoverConfig)))
}
