package hooks_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strconv"
	"testing"

	"github.com/pelletier/go-toml/v2"
	"github.com/qiz029/vibe-pushover/internal/hooks"
	"gopkg.in/yaml.v3"
)

func TestDefaultPathPiHonorsAgentDir(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "custom-pi-agent")
	t.Setenv("PI_CODING_AGENT_DIR", dir)
	t.Setenv("HOME", "")

	got, err := hooks.DefaultPath("pi")
	if err != nil {
		t.Fatalf("DefaultPath() error = %v", err)
	}
	want := filepath.Join(dir, "extensions", "vibe-pushover", "index.ts")
	if got != want {
		t.Fatalf("DefaultPath() = %q, want %q", got, want)
	}
}

func TestDefaultPathOMPHonorsAgentDir(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "custom-omp-agent")
	t.Setenv("PI_CODING_AGENT_DIR", dir)
	t.Setenv("HOME", "")

	got, err := hooks.DefaultPath("omp")
	if err != nil {
		t.Fatalf("DefaultPath() error = %v", err)
	}
	want := filepath.Join(dir, "extensions", "vibe-pushover", "index.ts")
	if got != want {
		t.Fatalf("DefaultPath() = %q, want %q", got, want)
	}
}

func TestDefaultPathsForAdditionalAgents(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("COPILOT_HOME", "~/copilot-home")
	t.Setenv("GEMINI_CLI_HOME", "~/gemini-home")
	t.Setenv("XDG_CONFIG_HOME", "~/.xdg")

	tests := map[string]string{
		"aider":    filepath.Join(home, ".aider.conf.yml"),
		"amp":      filepath.Join(home, ".config", "amp", "plugins", "vibe-pushover.ts"),
		"auggie":   filepath.Join(home, ".augment", "settings.json"),
		"copilot":  filepath.Join(home, "copilot-home", "hooks", "vibe-pushover.json"),
		"cortex":   filepath.Join(home, ".snowflake", "cortex", "hooks.json"),
		"droid":    filepath.Join(home, ".factory", "settings.json"),
		"gemini":   filepath.Join(home, "gemini-home", ".gemini", "settings.json"),
		"goose":    filepath.Join(home, ".agents", "plugins", "vibe-pushover"),
		"hermes":   filepath.Join(home, ".hermes", "config.yaml"),
		"kiro":     filepath.Join(home, ".kiro", "hooks", "vibe-pushover.json"),
		"opencode": filepath.Join(home, ".xdg", "opencode", "plugins", "vibe-pushover.ts"),
		"omp":      filepath.Join(home, ".omp", "agent", "extensions", "vibe-pushover", "index.ts"),
		"qoder":    filepath.Join(home, ".qoder", "settings.json"),
		"qwen":     filepath.Join(home, ".qwen", "settings.json"),
		"vscode":   filepath.Join(home, "copilot-home", "hooks", "vibe-pushover.json"),
		"windsurf": filepath.Join(home, ".codeium", "windsurf", "hooks.json"),
	}
	for agent, want := range tests {
		got, err := hooks.DefaultPath(agent)
		if err != nil {
			t.Fatalf("DefaultPath(%q) error = %v", agent, err)
		}
		if got != want {
			t.Errorf("DefaultPath(%q) = %q, want %q", agent, got, want)
		}
	}
}

func TestInstallConfiguresAiderNotificationCommand(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "home with spaces", ".aider.conf.yml")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	original := "# personal aider settings\nmodel: sonnet\nread:\n  - README.md\n# keep notification note\nnotifications: false\n"
	if err := os.WriteFile(path, []byte(original), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	changed, err := hooks.Install("aider", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	wrapperPath := filepath.Join(filepath.Dir(path), ".aider", "vibe-pushover-notify.sh")
	for _, want := range []string{
		"# personal aider settings",
		"# keep notification note",
		"model: sonnet",
		"- README.md",
		"notifications: true",
		wrapperPath,
	} {
		if !bytes.Contains(data, []byte(want)) {
			t.Fatalf("Aider config does not contain %q:\n%s", want, data)
		}
	}
	var parsed map[string]any
	if err := yaml.Unmarshal(data, &parsed); err != nil {
		t.Fatalf("Unmarshal(config) error = %v", err)
	}
	if parsed["notifications"] != true || parsed["notifications-command"] != "'"+wrapperPath+"'" {
		t.Fatalf("Aider notification settings = %#v", parsed)
	}
	wrapper, err := os.ReadFile(wrapperPath)
	if err != nil {
		t.Fatalf("ReadFile(wrapper) error = %v", err)
	}
	for _, want := range []string{
		"#!/bin/sh",
		"# Generated by vibe-pushover.",
		`{"message":"Aider is ready for input."}`,
		"'/opt/bin/vibe-pushover' notify --agent aider --event turn-complete --ignore-errors --config '/tmp/pushover.json'",
	} {
		if !bytes.Contains(wrapper, []byte(want)) {
			t.Fatalf("Aider wrapper does not contain %q:\n%s", want, wrapper)
		}
	}
	info, err := os.Stat(wrapperPath)
	if err != nil {
		t.Fatalf("Stat(wrapper) error = %v", err)
	}
	if info.Mode().Perm()&0o100 == 0 {
		t.Fatalf("wrapper mode = %o, want executable", info.Mode().Perm())
	}
	changed, err = hooks.Install("aider", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Aider integration")
	}
}

func TestInstallAiderAcceptsEmptyConfig(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".aider.conf.yml")
	if err := os.WriteFile(path, nil, 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("aider", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Contains(data, []byte("notifications: true")) {
		t.Fatalf("Aider config = %s", data)
	}
}

func TestInstallAiderRefusesUnownedWrapper(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, ".aider.conf.yml")
	wrapperPath := filepath.Join(dir, ".aider", "vibe-pushover-notify.sh")
	if err := os.MkdirAll(filepath.Dir(wrapperPath), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	original := []byte("#!/bin/sh\necho personal-script\n")
	if err := os.WriteFile(wrapperPath, original, 0o700); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("aider", path, "/opt/bin/vibe-pushover", ""); err == nil {
		t.Fatal("Install() overwrote an unowned Aider wrapper")
	}
	got, err := os.ReadFile(wrapperPath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Equal(got, original) {
		t.Fatalf("unowned wrapper changed: %q", got)
	}
	if _, err := os.Stat(path); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("Aider config exists after refused install: %v", err)
	}
}

func TestInstallAiderRefusesExistingNotificationCommand(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".aider.conf.yml")
	original := []byte("model: sonnet\nnotifications: true\nnotifications-command: personal-notifier\n")
	if err := os.WriteFile(path, original, 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("aider", path, "/opt/bin/vibe-pushover", ""); err == nil {
		t.Fatal("Install() replaced an existing Aider notification command")
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Equal(got, original) {
		t.Fatalf("Aider config changed after refused install: %s", got)
	}
	wrapperPath := filepath.Join(filepath.Dir(path), ".aider", "vibe-pushover-notify.sh")
	if _, err := os.Stat(wrapperPath); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("Aider wrapper exists after refused install: %v", err)
	}
}

func TestInstallCreatesAmpLifecyclePlugin(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".config", "amp", "plugins", "vibe-pushover.ts")
	changed, err := hooks.Install("amp", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	for _, want := range []string{
		"// Generated by vibe-pushover.",
		`amp.on("agent.start"`,
		`amp.on("agent.end"`,
		`event.status === "done"`,
		`ctx.thread.state.subscribe`,
		`state === "awaiting-approval"`,
		`amp.helpers.filePathFromURI(amp.system.workspaceRoot)`,
		`["notify", "--agent", "amp", "--event", eventName, "--ignore-errors"]`,
		`"approval-required"`,
		`"attention-required"`,
		`subscriptions.delete(event.thread.id)`,
		`last_assistant_message: assistantText(event.messages)`,
		`const configPath = "/tmp/pushover.json"`,
	} {
		if !bytes.Contains(data, []byte(want)) {
			t.Fatalf("Amp plugin does not contain %q:\n%s", want, data)
		}
	}
	changed, err = hooks.Install("amp", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Amp plugin")
	}
}

func TestInstallAmpRefusesUnownedPlugin(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "vibe-pushover.ts")
	original := []byte("// personal plugin\n// Generated by vibe-pushover.\n")
	if err := os.WriteFile(path, original, 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("amp", path, "/opt/bin/vibe-pushover", ""); err == nil {
		t.Fatal("Install() overwrote an unowned Amp plugin")
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Equal(got, original) {
		t.Fatalf("unowned plugin changed: %q", got)
	}
}

func TestInstallCreatesKiroCompletionHook(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".kiro", "hooks", "vibe-pushover.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(`{"version":"v1","hooks":[{"name":"keep","trigger":"PostFileSave","action":{"type":"command","command":"npm test"},"enabled":true}]}`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	changed, err := hooks.Install("kiro", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Version string           `json:"version"`
		Hooks   []map[string]any `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if got.Version != "v1" || len(got.Hooks) != 2 || got.Hooks[0]["name"] != "keep" {
		t.Fatalf("Kiro config did not preserve existing hooks: %#v", got)
	}
	owned := got.Hooks[1]
	action, _ := owned["action"].(map[string]any)
	wantCommand := "'/opt/bin/vibe-pushover' notify --agent kiro --event turn-complete --ignore-errors --config '/tmp/pushover.json'"
	if owned["name"] != "vibe-pushover-turn-complete" || owned["trigger"] != "Stop" || owned["timeout"] != float64(10) || owned["enabled"] != true || action["type"] != "command" || action["command"] != wantCommand {
		t.Fatalf("Kiro completion hook = %#v", owned)
	}
	changed, err = hooks.Install("kiro", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Kiro hook")
	}
}

func TestDefaultPathKimiUsesKimiCodeConfig(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	got, err := hooks.DefaultPath("kimi")
	if err != nil {
		t.Fatalf("DefaultPath() error = %v", err)
	}
	want := filepath.Join(home, ".kimi-code", "config.toml")
	if got != want {
		t.Fatalf("DefaultPath() = %q, want %q", got, want)
	}
}

func TestDefaultPathKimiHonorsKimiCodeHome(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("KIMI_CODE_HOME", "~/custom-kimi")

	got, err := hooks.DefaultPath("kimi")
	if err != nil {
		t.Fatalf("DefaultPath() error = %v", err)
	}
	want := filepath.Join(home, "custom-kimi", "config.toml")
	if got != want {
		t.Fatalf("DefaultPath() = %q, want %q", got, want)
	}
}

func TestDefaultPathPiExpandsTildeAgentDir(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("PI_CODING_AGENT_DIR", "~/.custom-pi")

	got, err := hooks.DefaultPath("pi")
	if err != nil {
		t.Fatalf("DefaultPath() error = %v", err)
	}
	want := filepath.Join(home, ".custom-pi", "extensions", "vibe-pushover", "index.ts")
	if got != want {
		t.Fatalf("DefaultPath() = %q, want %q", got, want)
	}
}

func TestInstallAddsCodexHooks(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".codex", "hooks.json")
	changed, err := hooks.Install("codex", path, "/usr/local/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Hooks map[string][]json.RawMessage `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if len(got.Hooks["Stop"]) != 1 {
		t.Fatalf("Stop hook count = %d, want 1", len(got.Hooks["Stop"]))
	}
	if len(got.Hooks["PermissionRequest"]) != 1 {
		t.Fatalf("PermissionRequest hook count = %d, want 1", len(got.Hooks["PermissionRequest"]))
	}
}

func TestInstallAddsGeminiTurnCompleteHook(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".gemini", "settings.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(`{"theme":"dark","hooks":{"BeforeTool":[{"hooks":[{"type":"command","command":"existing"}]}]}}`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	changed, err := hooks.Install("gemini", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Hooks map[string][]json.RawMessage `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if len(got.Hooks["AfterAgent"]) != 1 {
		t.Fatalf("AfterAgent hook count = %d, want 1", len(got.Hooks["AfterAgent"]))
	}
	if len(got.Hooks["BeforeTool"]) != 1 || !bytes.Contains(data, []byte(`"theme": "dark"`)) {
		t.Fatalf("Gemini install did not preserve sibling config: %s", data)
	}
	if bytes.Contains(data, []byte("PermissionRequest")) {
		t.Fatalf("Gemini config contains an unsupported permission hook: %s", data)
	}
	if bytes.Contains(data, []byte(`"async"`)) {
		t.Fatalf("Gemini config contains a Claude-specific async field: %s", data)
	}
	if !bytes.Contains(data, []byte(`"timeout": 10000`)) {
		t.Fatalf("Gemini hook timeout is not expressed in milliseconds: %s", data)
	}
	changed, err = hooks.Install("gemini", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Gemini hooks")
	}
}

func TestInstallAddsQwenCompletionApprovalAndIdleAttentionHooks(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".qwen", "settings.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(`{"theme":"dark","hooks":{"BeforeToolUse":[{"hooks":[{"type":"command","command":"existing"}]}]}}`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	changed, err := hooks.Install("qwen", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Hooks map[string][]map[string]any `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	for _, event := range []string{"Stop", "PermissionRequest", "Notification"} {
		if len(got.Hooks[event]) != 1 {
			t.Fatalf("%s hook count = %d, want 1", event, len(got.Hooks[event]))
		}
		commands, _ := got.Hooks[event][0]["hooks"].([]any)
		command, _ := commands[0].(map[string]any)
		if command["timeout"] != float64(10000) || command["async"] != true {
			t.Fatalf("%s command = %#v, want 10000ms async hook", event, command)
		}
	}
	if got.Hooks["Notification"][0]["matcher"] != "idle_prompt" {
		t.Fatalf("Notification matcher = %#v, want idle_prompt", got.Hooks["Notification"][0]["matcher"])
	}
	for _, want := range []string{
		"--agent qwen --event turn-complete",
		"--skip-active-qwen-stop",
		"--agent qwen --event approval-required",
		"--agent qwen --event attention-required",
		"--config '/tmp/pushover.json'",
		`"theme": "dark"`,
		`"BeforeToolUse"`,
	} {
		if !bytes.Contains(data, []byte(want)) {
			t.Fatalf("Qwen config does not contain %q:\n%s", want, data)
		}
	}
	changed, err = hooks.Install("qwen", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Qwen hooks")
	}
}

func TestInstallAddsQoderCompletionHook(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".qoder", "settings.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(`{"theme":"dark","hooks":{"Stop":[{"hooks":[{"type":"command","command":"existing"}]}]}}`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	changed, err := hooks.Install("qoder", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	for _, want := range []string{
		`"theme": "dark"`,
		`"command": "existing"`,
		"--agent qoder --event turn-complete --ignore-errors --skip-active-stop",
		`"timeout": 10`,
		"--config '/tmp/pushover.json'",
	} {
		if !bytes.Contains(data, []byte(want)) {
			t.Fatalf("Qoder config does not contain %q:\n%s", want, data)
		}
	}
	changed, err = hooks.Install("qoder", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Qoder hooks")
	}
}

func TestInstallAddsCortexCompletionAndApprovalHooks(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".snowflake", "cortex", "hooks.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(`{"theme":"dark","hooks":{"PreToolUse":[{"matcher":"Bash","hooks":[{"type":"command","command":"existing"}]}]}}`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	changed, err := hooks.Install("cortex", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Hooks map[string][]map[string]any `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	for _, event := range []string{"Stop", "PermissionRequest"} {
		if len(got.Hooks[event]) != 1 {
			t.Fatalf("%s hook count = %d, want 1", event, len(got.Hooks[event]))
		}
		commands, _ := got.Hooks[event][0]["hooks"].([]any)
		command, _ := commands[0].(map[string]any)
		if command["timeout"] != float64(10) {
			t.Fatalf("%s timeout = %#v, want 10 seconds", event, command["timeout"])
		}
		if _, exists := command["async"]; exists {
			t.Fatalf("%s command unexpectedly contains unsupported async field: %#v", event, command)
		}
	}
	for _, want := range []string{
		`"theme": "dark"`, `"command": "existing"`,
		"--agent cortex --event turn-complete --ignore-errors",
		"--agent cortex --event approval-required --ignore-errors",
		"--config '/tmp/pushover.json'",
	} {
		if !bytes.Contains(data, []byte(want)) {
			t.Fatalf("Cortex config does not contain %q:\n%s", want, data)
		}
	}
	changed, err = hooks.Install("cortex", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Cortex hooks")
	}
}

func TestInstallAddsOhMyPiCompletionAndApprovalExtension(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".omp", "agent", "extensions", "vibe-pushover", "index.ts")
	changed, err := hooks.Install("omp", path, "/opt/bin/vibe-pushover", "/tmp/pushover config.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	for _, want := range []string{
		`pi.on("agent_end"`, `event.willContinue`, `lastAssistantText(event.messages)`,
		`pi.on("tool_approval_requested"`, `tool_name: event.toolName`, `reason: event.reason`,
		`"--agent"`, `"omp"`, `"turn-complete"`, `"approval-required"`,
		`const configPath = "/tmp/pushover config.json"`,
	} {
		if !bytes.Contains(data, []byte(want)) {
			t.Fatalf("Oh My Pi extension does not contain %q:\n%s", want, data)
		}
	}
	changed, err = hooks.Install("omp", path, "/opt/bin/vibe-pushover", "/tmp/pushover config.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Oh My Pi extension")
	}
}

func TestInstallRefusesToOverwriteUnownedOhMyPiExtension(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "index.ts")
	if err := os.WriteFile(path, []byte("export default function custom() {}\n"), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	changed, err := hooks.Install("omp", path, "/opt/bin/vibe-pushover", "")
	if err == nil || changed {
		t.Fatalf("Install() = changed %v, error %v; want refusal", changed, err)
	}
	data, readErr := os.ReadFile(path)
	if readErr != nil {
		t.Fatalf("ReadFile() error = %v", readErr)
	}
	if string(data) != "export default function custom() {}\n" {
		t.Fatalf("unowned extension was modified: %q", data)
	}
}

func TestInstallAddsHermesCompletionAndApprovalHooks(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".hermes", "config.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	original := "# personal config\nmodel: nous\nhooks:\n  pre_tool_call:\n    - matcher: terminal\n      command: /usr/local/bin/check-hook\n"
	if err := os.WriteFile(path, []byte(original), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	changed, err := hooks.Install("hermes", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	for _, want := range []string{
		"# personal config", "model: nous", "pre_tool_call:", "command: /usr/local/bin/check-hook",
		"post_llm_call:", "--agent hermes --event turn-complete --ignore-errors",
		"pre_approval_request:", "--agent hermes --event approval-required --ignore-errors --skip-noninteractive-approval",
		"timeout: 10", "--config '/tmp/pushover.json'",
	} {
		if !bytes.Contains(data, []byte(want)) {
			t.Fatalf("Hermes config does not contain %q:\n%s", want, data)
		}
	}
	var decoded map[string]any
	if err := yaml.Unmarshal(data, &decoded); err != nil {
		t.Fatalf("YAML is invalid: %v", err)
	}
	changed, err = hooks.Install("hermes", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Hermes hooks")
	}
}

func TestInstallHermesReportsHermesForMalformedHook(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".hermes", "config.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte("hooks:\n  post_llm_call:\n    - command:\n        nested: invalid\n"), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	_, err := hooks.Install("hermes", path, "/opt/bin/vibe-pushover", "")
	if err == nil {
		t.Fatal("Install() error = nil, want malformed Hermes hook error")
	}
	if !bytes.Contains([]byte(err.Error()), []byte("Hermes hook")) || bytes.Contains([]byte(err.Error()), []byte("Aider")) {
		t.Fatalf("Install() error = %q, want Hermes-specific context", err)
	}
}

func TestInstallAddsDroidCompletionAndAttentionHooks(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".factory", "settings.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(`{"model":"fast","hooks":{"PreToolUse":[{"hooks":[{"type":"command","command":"existing"}]}]}}`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("droid", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Hooks map[string][]json.RawMessage `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if len(got.Hooks["Stop"]) != 1 || len(got.Hooks["Notification"]) != 1 {
		t.Fatalf("hooks = %#v, want Stop and Notification", got.Hooks)
	}
	if len(got.Hooks["PreToolUse"]) != 1 || !bytes.Contains(data, []byte(`"model": "fast"`)) {
		t.Fatalf("Droid install did not preserve sibling config: %s", data)
	}
	if !bytes.Contains(data, []byte("--agent droid --event attention-required")) {
		t.Fatalf("Notification hook is not wired to attention-required: %s", data)
	}
	if bytes.Contains(data, []byte(`"async"`)) {
		t.Fatalf("Droid config contains a Claude-specific async field: %s", data)
	}
	changed, err := hooks.Install("droid", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Droid hooks")
	}
}

func TestInstallAddsCopilotPersonalHooks(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".copilot", "hooks", "vibe-pushover.json")
	if _, err := hooks.Install("copilot", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json"); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Version int                         `json:"version"`
		Hooks   map[string][]map[string]any `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if got.Version != 1 || len(got.Hooks["agentStop"]) != 1 || len(got.Hooks["notification"]) != 1 {
		t.Fatalf("Copilot manifest = %#v", got)
	}
	for _, event := range []string{"agentStop", "notification"} {
		if got.Hooks[event][0]["type"] != "command" || got.Hooks[event][0]["timeoutSec"] != float64(10) {
			t.Fatalf("%s hook = %#v", event, got.Hooks[event][0])
		}
	}
	if got.Hooks["notification"][0]["matcher"] != "permission_prompt|elicitation_dialog" {
		t.Fatalf("notification matcher = %#v", got.Hooks["notification"][0]["matcher"])
	}
	if !bytes.Contains(data, []byte("--event attention-required")) {
		t.Fatalf("Copilot attention hook is not wired correctly: %s", data)
	}
	if !bytes.Contains(data, []byte("--config '/tmp/pushover.json'")) {
		t.Fatalf("Copilot hooks do not use custom config: %s", data)
	}
	changed, err := hooks.Install("copilot", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Copilot hooks")
	}
}

func TestInstallCreatesGooseOpenPlugin(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".agents", "plugins", "vibe-pushover")
	if _, err := hooks.Install("goose", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	manifest, err := os.ReadFile(filepath.Join(path, "plugin.json"))
	if err != nil {
		t.Fatalf("ReadFile(plugin.json) error = %v", err)
	}
	if !bytes.Contains(manifest, []byte(`"name": "vibe-pushover"`)) {
		t.Fatalf("unexpected Goose plugin manifest: %s", manifest)
	}
	hookData, err := os.ReadFile(filepath.Join(path, "hooks", "hooks.json"))
	if err != nil {
		t.Fatalf("ReadFile(hooks.json) error = %v", err)
	}
	if !bytes.Contains(hookData, []byte(`"Stop"`)) || !bytes.Contains(hookData, []byte("--agent goose --event turn-complete")) {
		t.Fatalf("unexpected Goose hooks: %s", hookData)
	}
	changed, err := hooks.Install("goose", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Goose plugin")
	}
}

func TestInstallGooseDoesNotWriteManifestWhenHooksAreInvalid(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".agents", "plugins", "vibe-pushover")
	hooksPath := filepath.Join(path, "hooks", "hooks.json")
	if err := os.MkdirAll(filepath.Dir(hooksPath), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(hooksPath, []byte(`{"hooks":`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("goose", path, "/opt/bin/vibe-pushover", ""); err == nil {
		t.Fatal("Install() accepted invalid Goose hooks")
	}
	if _, err := os.Stat(filepath.Join(path, "plugin.json")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("plugin manifest exists after failed install: %v", err)
	}
}

func TestInstallCreatesOpenCodePlugin(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "opencode", "plugins", "vibe-pushover.ts")
	if _, err := hooks.Install("opencode", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json"); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	for _, want := range []string{
		`event.type === "session.idle"`,
		`event.type === "permission.asked"`,
		`"--agent", "opencode"`,
		`"--config", configPath`,
	} {
		if !bytes.Contains(data, []byte(want)) {
			t.Fatalf("OpenCode plugin does not contain %q:\n%s", want, data)
		}
	}
	changed, err := hooks.Install("opencode", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed OpenCode plugin")
	}
}

func TestInstallAddsCursorStopHook(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".cursor", "hooks.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(`{"version":1,"hooks":{"afterFileEdit":[{"command":"existing"}]}}`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("cursor", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Version int                         `json:"version"`
		Hooks   map[string][]map[string]any `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if got.Version != 1 || len(got.Hooks["stop"]) != 1 || len(got.Hooks["afterFileEdit"]) != 1 {
		t.Fatalf("Cursor config = %#v", got)
	}
	if got.Hooks["stop"][0]["command"] != "'/opt/bin/vibe-pushover' notify --agent cursor --event turn-complete --ignore-errors" {
		t.Fatalf("Cursor stop hook = %#v", got.Hooks["stop"][0])
	}
	changed, err := hooks.Install("cursor", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Cursor hooks")
	}
}

func TestInstallAddsWindsurfPostResponseHook(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".codeium", "windsurf", "hooks.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(`{"hooks":{"post_read_code":[{"command":"existing","show_output":true}]}}`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	changed, err := hooks.Install("windsurf", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Hooks map[string][]map[string]any `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if len(got.Hooks["post_cascade_response"]) != 1 || len(got.Hooks["post_read_code"]) != 1 {
		t.Fatalf("Windsurf hooks = %#v", got.Hooks)
	}
	wantCommand := "'/opt/bin/vibe-pushover' notify --agent windsurf --event turn-complete --ignore-errors --config '/tmp/pushover.json'"
	if got.Hooks["post_cascade_response"][0]["command"] != wantCommand || got.Hooks["post_cascade_response"][0]["show_output"] != false {
		t.Fatalf("post_cascade_response hook = %#v", got.Hooks["post_cascade_response"][0])
	}
	changed, err = hooks.Install("windsurf", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Windsurf hooks")
	}
}

func TestInstallAddsVSCodeAgentStopHook(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".copilot", "hooks", "vibe-pushover.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(`{"version":1,"hooks":{"userPromptSubmitted":[{"type":"command","bash":"existing"}]}}`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	changed, err := hooks.Install("vscode", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Version int                         `json:"version"`
		Hooks   map[string][]map[string]any `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if got.Version != 1 || len(got.Hooks["agentStop"]) != 1 || len(got.Hooks["userPromptSubmitted"]) != 1 {
		t.Fatalf("VS Code hooks = %#v", got.Hooks)
	}
	stop := got.Hooks["agentStop"][0]
	if stop["type"] != "command" || stop["timeoutSec"] != float64(10) || stop["bash"] != "'/opt/bin/vibe-pushover' notify --agent copilot-vscode --event turn-complete --ignore-errors" {
		t.Fatalf("VS Code Stop hook = %#v", stop)
	}
	changed, err = hooks.Install("vscode", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed VS Code hooks")
	}
}

func TestInstallCopilotAndVSCodeShareManifestWithoutDuplicateCompletion(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".copilot", "hooks", "vibe-pushover.json")
	if _, err := hooks.Install("copilot", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install(copilot) error = %v", err)
	}
	changed, err := hooks.Install("vscode", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("Install(vscode) error = %v", err)
	}
	if changed {
		t.Fatal("VS Code install duplicated the shared Copilot manifest")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Hooks map[string][]map[string]any `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if len(got.Hooks["agentStop"]) != 1 {
		t.Fatalf("shared completion hook count = %d, want 1", len(got.Hooks["agentStop"]))
	}
}

func TestInstallAddsAuggieCompletionHookAndWrapper(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "home with spaces", ".augment", "settings.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(`{"model":"fast","hooks":{"SessionStart":[{"hooks":[{"type":"command","command":"/tmp/existing.sh"}]}]}}`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	changed, err := hooks.Install("auggie", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(settings) error = %v", err)
	}
	var got struct {
		Hooks map[string][]map[string]any `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if len(got.Hooks["Stop"]) != 1 || len(got.Hooks["SessionStart"]) != 1 || !bytes.Contains(data, []byte(`"model": "fast"`)) {
		t.Fatalf("Auggie settings did not preserve sibling config: %s", data)
	}
	stop := got.Hooks["Stop"][0]
	metadata, _ := stop["metadata"].(map[string]any)
	commands, _ := stop["hooks"].([]any)
	command, _ := commands[0].(map[string]any)
	wrapperPath := filepath.Join(filepath.Dir(path), "hooks", "vibe-pushover.sh")
	if command["type"] != "command" || command["command"] != "'"+wrapperPath+"'" || command["timeout"] != float64(10000) || metadata["includeConversationData"] != true {
		t.Fatalf("Auggie Stop hook = %#v", stop)
	}
	wrapper, err := os.ReadFile(wrapperPath)
	if err != nil {
		t.Fatalf("ReadFile(wrapper) error = %v", err)
	}
	for _, want := range []string{
		"# Generated by vibe-pushover.",
		"'/opt/bin/vibe-pushover' notify --agent auggie --event turn-complete --skip-non-completion --ignore-errors",
		"--config '/tmp/pushover.json'",
	} {
		if !bytes.Contains(wrapper, []byte(want)) {
			t.Fatalf("Auggie wrapper does not contain %q:\n%s", want, wrapper)
		}
	}
	info, err := os.Stat(wrapperPath)
	if err != nil {
		t.Fatalf("Stat(wrapper) error = %v", err)
	}
	if info.Mode().Perm()&0o100 == 0 {
		t.Fatalf("wrapper mode = %o, want executable", info.Mode().Perm())
	}
	changed, err = hooks.Install("auggie", path, "/opt/bin/vibe-pushover", "/tmp/pushover.json")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed Auggie integration")
	}
}

func TestInstallAuggiePreservesOwnedGroupSiblings(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".augment", "settings.json")
	wrapperPath := filepath.Join(filepath.Dir(path), "hooks", "vibe-pushover.sh")
	original := map[string]any{
		"hooks": map[string]any{
			"Stop": []any{map[string]any{
				"hooks": []any{
					map[string]any{"type": "command", "command": wrapperPath, "timeout": 1, "custom": "keep-command"},
					map[string]any{"type": "command", "command": "/tmp/keep.sh"},
				},
				"metadata": map[string]any{"custom": "keep-metadata"},
				"custom":   "keep-group",
			}},
		},
	}
	data, err := json.Marshal(original)
	if err != nil {
		t.Fatalf("Marshal() error = %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		t.Fatalf("WriteFile(settings) error = %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(wrapperPath), 0o700); err != nil {
		t.Fatalf("MkdirAll(wrapper) error = %v", err)
	}
	if err := os.WriteFile(wrapperPath, []byte("#!/bin/sh\n# Generated by vibe-pushover.\nexit 0\n"), 0o700); err != nil {
		t.Fatalf("WriteFile(wrapper) error = %v", err)
	}

	if _, err := hooks.Install("auggie", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err = os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(settings) error = %v", err)
	}
	var got map[string]any
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	hookMap := got["hooks"].(map[string]any)
	group := hookMap["Stop"].([]any)[0].(map[string]any)
	commands := group["hooks"].([]any)
	metadata := group["metadata"].(map[string]any)
	owned := commands[0].(map[string]any)
	if len(commands) != 2 || commands[1].(map[string]any)["command"] != "/tmp/keep.sh" {
		t.Fatalf("sibling commands were not preserved: %#v", commands)
	}
	if group["custom"] != "keep-group" || metadata["custom"] != "keep-metadata" || owned["custom"] != "keep-command" {
		t.Fatalf("unknown Auggie fields were not preserved: %#v", group)
	}
	if owned["command"] != "'"+wrapperPath+"'" || owned["timeout"] != float64(10000) || metadata["includeConversationData"] != true {
		t.Fatalf("owned Auggie hook was not updated: %#v", group)
	}
}

func TestInstallAuggieRefusesMarkerOutsideGeneratedPrefix(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".augment", "settings.json")
	wrapperPath := filepath.Join(filepath.Dir(path), "hooks", "vibe-pushover.sh")
	if err := os.MkdirAll(filepath.Dir(wrapperPath), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	original := []byte("#!/bin/sh\necho '# Generated by vibe-pushover.'\n")
	if err := os.WriteFile(wrapperPath, original, 0o700); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("auggie", path, "/opt/bin/vibe-pushover", ""); err == nil {
		t.Fatal("Install() overwrote a non-owned Auggie wrapper")
	}
	after, err := os.ReadFile(wrapperPath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Equal(after, original) {
		t.Fatal("non-owned Auggie wrapper changed")
	}
}

func TestInstallAddsKimiHooksAndPreservesConfig(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".kimi-code", "config.toml")
	original := `theme = "dark"

[[hooks]]
event = "StopFailure"
command = "existing-hook"
timeout = 10
`
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(original), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	changed, err := hooks.Install("kimi", path, "/opt/bin/vibe-pushover", "/tmp/pushover config.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	for _, want := range []string{
		original,
		`event = "Stop"`,
		`--agent kimi --event turn-complete --ignore-errors --config '/tmp/pushover config.json'`,
		`event = "PermissionRequest"`,
		`--agent kimi --event approval-required --ignore-errors --config '/tmp/pushover config.json'`,
	} {
		if !bytes.Contains(data, []byte(want)) {
			t.Fatalf("Kimi config does not contain %q:\n%s", want, data)
		}
	}
	if got := bytes.Count(data, []byte("[[hooks]]")); got != 3 {
		t.Fatalf("hook count = %d, want 3", got)
	}
}

func TestInstallKimiHooksIsIdempotent(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "config.toml")
	if _, err := hooks.Install("kimi", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("first Install() error = %v", err)
	}
	before, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}

	changed, err := hooks.Install("kimi", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed = true, want false")
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Equal(after, before) {
		t.Fatal("second Install() rewrote the Kimi config")
	}
}

func TestInstallKimiHooksConvertsInlineHooksAndPreservesEntries(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "config.toml")
	original := []byte(`# keep this comment
theme = "dark"
hooks = [
  { event = "StopFailure", command = "echo '] # still a string'", timeout = 10 }, # keep hook
]
`)
	if err := os.WriteFile(path, original, 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	if _, err := hooks.Install("kimi", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Contains(data, []byte("# keep this comment")) {
		t.Fatalf("Install() dropped unrelated comments:\n%s", data)
	}
	var got struct {
		Theme string `toml:"theme"`
		Hooks []struct {
			Event   string `toml:"event"`
			Command string `toml:"command"`
			Timeout int    `toml:"timeout"`
		} `toml:"hooks"`
	}
	if err := toml.Unmarshal(data, &got); err != nil {
		t.Fatalf("generated config is invalid TOML: %v\n%s", err, data)
	}
	if got.Theme != "dark" {
		t.Fatalf("theme = %q, want dark", got.Theme)
	}
	if len(got.Hooks) != 3 {
		t.Fatalf("hook count = %d, want 3", len(got.Hooks))
	}
	if got.Hooks[0].Event != "StopFailure" || got.Hooks[0].Command != "echo '] # still a string'" || got.Hooks[0].Timeout != 10 {
		t.Fatalf("existing hook was not preserved: %#v", got.Hooks[0])
	}
	if !bytes.Contains(data, []byte("# keep hook")) {
		t.Fatalf("inline hook comment was removed:\n%s", data)
	}
	changed, err := hooks.Install("kimi", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed inline hooks")
	}
}

func TestInstallKimiHooksConvertsEmptyInlineHooks(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "config.toml")
	if err := os.WriteFile(path, []byte("hooks = []\n"), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("kimi", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Hooks []map[string]any `toml:"hooks"`
	}
	if err := toml.Unmarshal(data, &got); err != nil {
		t.Fatalf("generated config is invalid TOML: %v\n%s", err, data)
	}
	if len(got.Hooks) != 2 {
		t.Fatalf("hook count = %d, want 2", len(got.Hooks))
	}
}

func TestInstallKimiHooksRecognizesQuotedArrayTable(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "config.toml")
	original := []byte("[[\"hooks\"]]\nevent = \"StopFailure\"\ncommand = \"echo keep\"\n")
	if err := os.WriteFile(path, original, 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("kimi", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Contains(data, original) || bytes.Count(data, []byte("[[hooks]]")) != 2 {
		t.Fatalf("quoted existing hook was not preserved:\n%s", data)
	}
}

func TestInstallKimiHooksIgnoresHookHeaderInsideMultilineString(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "config.toml")
	original := []byte("note = '''\n[[hooks]]\n'''\nhooks = []\n")
	if err := os.WriteFile(path, original, 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("kimi", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var parsed map[string]any
	if err := toml.Unmarshal(data, &parsed); err != nil {
		t.Fatalf("generated config is invalid: %v\n%s", err, data)
	}
	hookList, ok := parsed["hooks"].([]any)
	if !ok || len(hookList) != 2 {
		t.Fatalf("hooks = %#v, want two installed hooks", parsed["hooks"])
	}
}

func TestInstallKimiHooksPreservesConfigSymlink(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	target := filepath.Join(dir, "dotfiles", "kimi.toml")
	if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(target, []byte("theme = \"dark\"\n"), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	path := filepath.Join(dir, "config.toml")
	if err := os.Symlink(target, path); err != nil {
		t.Fatalf("Symlink() error = %v", err)
	}

	if _, err := hooks.Install("kimi", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	info, err := os.Lstat(path)
	if err != nil {
		t.Fatalf("Lstat() error = %v", err)
	}
	if info.Mode()&os.ModeSymlink == 0 {
		t.Fatal("Install() replaced the Kimi config symlink")
	}
	data, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("ReadFile(target) error = %v", err)
	}
	if !bytes.Contains(data, []byte(`event = "Stop"`)) {
		t.Fatalf("symlink target was not updated: %s", data)
	}
}

func TestInstallIsIdempotent(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "settings.json")
	if _, err := hooks.Install("claude", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("first Install() error = %v", err)
	}
	before, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}

	changed, err := hooks.Install("claude", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed = true, want false")
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if string(after) != string(before) {
		t.Fatal("second Install() rewrote the config")
	}
}

func TestInstallPreservesExistingSettingsAndHooks(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "settings.json")
	if err := os.WriteFile(path, []byte(`{
  "theme": "dark",
  "hooks": {
    "Stop": [{"hooks": [{"type": "command", "command": "existing-hook"}]}]
  }
}`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	if _, err := hooks.Install("claude", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	var got struct {
		Theme string `json:"theme"`
		Hooks struct {
			Stop []json.RawMessage `json:"Stop"`
		} `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if got.Theme != "dark" {
		t.Fatalf("theme = %q, want dark", got.Theme)
	}
	if len(got.Hooks.Stop) != 2 {
		t.Fatalf("Stop hook count = %d, want 2", len(got.Hooks.Stop))
	}
}

func TestInstallPassesCustomPushoverConfigToHook(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "hooks.json")
	_, err := hooks.Install("codex", path, "/opt/bin/vibe-pushover", "/tmp/custom config.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Contains(data, []byte(`--config '/tmp/custom config.json'`)) {
		t.Fatalf("installed hooks do not contain custom config path: %s", data)
	}
}

func TestInstallPreservesLargeJSONNumbers(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "settings.json")
	const original = `{"large_id":9007199254740993}`
	if err := os.WriteFile(path, []byte(original), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("claude", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Contains(data, []byte(`9007199254740993`)) {
		t.Fatalf("large JSON number was changed: %s", data)
	}
}

func TestInstallRejectsNullAgentConfig(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "settings.json")
	if err := os.WriteFile(path, []byte("null"), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("claude", path, "/opt/bin/vibe-pushover", ""); err == nil {
		t.Fatal("Install() error = nil, want invalid top-level config error")
	}
}

func TestInstallUpdatesOwnedCommandWithoutDroppingSiblingHook(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "hooks.json")
	config := `{"hooks":{"Stop":[{"hooks":[{"type":"command","command":"'/old/bin' notify --agent codex --event turn-complete --ignore-errors"},{"type":"command","command":"existing-hook"}]}]}}`
	if err := os.WriteFile(path, []byte(config), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("codex", path, "/new/bin", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Contains(data, []byte("existing-hook")) {
		t.Fatalf("sibling hook was removed: %s", data)
	}
	if !bytes.Contains(data, []byte("'/new/bin' notify")) {
		t.Fatalf("owned hook was not updated: %s", data)
	}
}

func TestInstallDoesNotReplaceCompositeCommandContainingMarker(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "hooks.json")
	composite := `'/bin/sh' -c "log-and-run vibe-pushover notify --agent codex --event turn-complete"`
	config := `{"hooks":{"Stop":[{"hooks":[{"type":"command","command":` + strconv.Quote(composite) + `}]}]}}`
	if err := os.WriteFile(path, []byte(config), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("codex", path, "/new/bin", ""); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Contains(data, []byte("log-and-run")) {
		t.Fatalf("unrelated composite hook was replaced: %s", data)
	}
	var got struct {
		Hooks map[string][]json.RawMessage `json:"hooks"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if len(got.Hooks["Stop"]) != 2 {
		t.Fatalf("Stop hook count = %d, want 2", len(got.Hooks["Stop"]))
	}
}

func TestInstallAddsPiTurnCompleteExtension(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), ".pi", "agent", "extensions", "vibe-pushover", "index.ts")
	changed, err := hooks.Install("pi", path, "/opt/bin/vibe-pushover", "/tmp/pushover config.json")
	if err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	if !changed {
		t.Fatal("Install() changed = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	for _, want := range []string{
		`pi.on("agent_settled"`,
		`"/opt/bin/vibe-pushover"`,
		`"/tmp/pushover config.json"`,
		`"turn-complete"`,
	} {
		if !bytes.Contains(data, []byte(want)) {
			t.Fatalf("Pi extension does not contain %q: %s", want, data)
		}
	}
}

func TestInstallPiExtensionIsIdempotent(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "index.ts")
	if _, err := hooks.Install("pi", path, "/opt/bin/vibe-pushover", ""); err != nil {
		t.Fatalf("first Install() error = %v", err)
	}
	before, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	changed, err := hooks.Install("pi", path, "/opt/bin/vibe-pushover", "")
	if err != nil {
		t.Fatalf("second Install() error = %v", err)
	}
	if changed {
		t.Fatal("second Install() changed = true, want false")
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !bytes.Equal(after, before) {
		t.Fatal("second Install() rewrote the Pi extension")
	}
}

func TestInstallPiExtensionRefusesToOverwriteForeignFile(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "index.ts")
	if err := os.WriteFile(path, []byte("export default function custom() {}\n"), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := hooks.Install("pi", path, "/opt/bin/vibe-pushover", ""); err == nil {
		t.Fatal("Install() error = nil, want foreign-file protection error")
	}
}
