package hooks

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

const ompExtensionMarker = "// Generated by vibe-pushover for Oh My Pi."

func installOMPExtension(path, executable, pushoverConfig string) (bool, error) {
	content, err := renderOMPExtension(executable, pushoverConfig)
	if err != nil {
		return false, err
	}
	existing, err := os.ReadFile(path)
	if err == nil {
		if bytes.Equal(existing, content) {
			return false, nil
		}
		if !bytes.HasPrefix(existing, []byte(ompExtensionMarker)) {
			return false, fmt.Errorf("refusing to overwrite Oh My Pi extension not owned by vibe-pushover: %s", path)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read Oh My Pi extension: %w", err)
	}
	if err := writeOMPExtension(path, content); err != nil {
		return false, err
	}
	return true, nil
}

func renderOMPExtension(executable, pushoverConfig string) ([]byte, error) {
	binaryJSON, err := json.Marshal(executable)
	if err != nil {
		return nil, fmt.Errorf("encode executable path: %w", err)
	}
	configJSON, err := json.Marshal(pushoverConfig)
	if err != nil {
		return nil, fmt.Errorf("encode config path: %w", err)
	}
	content := fmt.Sprintf(`%s
import { spawn } from "node:child_process";

const binary = %s;
const configPath = %s;

function assistantText(message) {
  if (!message || message.role !== "assistant") return "";
  if (typeof message.content === "string") return message.content;
  if (!Array.isArray(message.content)) return "";
  return message.content
    .filter((part) => part && part.type === "text" && typeof part.text === "string")
    .map((part) => part.text)
    .join("");
}

function lastAssistantText(messages) {
  if (!Array.isArray(messages)) return "";
  for (let index = messages.length - 1; index >= 0; index--) {
    const text = assistantText(messages[index]);
    if (text) return text;
  }
  return "";
}

function notify(event, payload) {
  const args = ["notify", "--agent", "omp", "--event", event, "--ignore-errors"];
  if (configPath) args.push("--config", configPath);
  const child = spawn(binary, args, {
    detached: true,
    stdio: ["pipe", "ignore", "inherit"],
  });
  child.on("error", (error) => {
    console.error("[vibe-pushover] failed to start notifier:", error.message);
  });
  child.stdin.on("error", (error) => {
    console.error("[vibe-pushover] failed to send hook payload:", error.message);
  });
  child.stdin.end(JSON.stringify(payload));
  child.unref();
}

export default function (pi) {
  pi.on("agent_end", (event, ctx) => {
    if (event.willContinue) return;
    notify("turn-complete", {
      cwd: ctx.cwd,
      last_assistant_message: lastAssistantText(event.messages),
    });
  });

  pi.on("tool_approval_requested", (event, ctx) => {
    notify("approval-required", {
      cwd: ctx.cwd,
      session_id: event.sessionId,
      tool_call_id: event.toolCallId,
      tool_name: event.toolName,
      reason: event.reason,
      approval_mode: event.approvalMode,
    });
  });
}
`, ompExtensionMarker, binaryJSON, configJSON)
	return []byte(content), nil
}

func writeOMPExtension(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create Oh My Pi extension directory: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".vibe-pushover-*.ts")
	if err != nil {
		return fmt.Errorf("create temporary Oh My Pi extension: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return fmt.Errorf("set Oh My Pi extension permissions: %w", err)
	}
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		return fmt.Errorf("write Oh My Pi extension: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close Oh My Pi extension: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replace Oh My Pi extension: %w", err)
	}
	return nil
}
