package hooks

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const openCodePluginMarker = "// Generated by vibe-pushover."

func installOpenCodePlugin(path, executable, pushoverConfig, agent, displayName string, moduleDescriptor bool) (bool, error) {
	resolvedPath, err := resolveOpenCodePluginPath(path, displayName)
	if err != nil {
		return false, err
	}
	path = resolvedPath
	content, err := renderOpenCodePlugin(executable, pushoverConfig, agent, moduleDescriptor)
	if err != nil {
		return false, err
	}
	existing, err := os.ReadFile(path)
	if err == nil {
		if bytes.Equal(existing, content) {
			return false, nil
		}
		if !bytes.HasPrefix(existing, []byte(openCodePluginMarker)) {
			return false, fmt.Errorf("refusing to overwrite %s plugin not owned by vibe-pushover: %s", displayName, path)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read %s plugin: %w", displayName, err)
	}
	if err := writeGeneratedFile(path, content, ".vibe-pushover-*.ts"); err != nil {
		return false, err
	}
	return true, nil
}

func resolveOpenCodePluginPath(path, displayName string) (string, error) {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return path, nil
	}
	if err != nil {
		return "", fmt.Errorf("inspect %s plugin: %w", displayName, err)
	}
	if info.Mode()&os.ModeSymlink == 0 {
		return path, nil
	}
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil {
		return "", fmt.Errorf("resolve %s plugin symlink: %w", displayName, err)
	}
	return resolved, nil
}

func renderOpenCodePlugin(executable, pushoverConfig, agent string, moduleDescriptor bool) ([]byte, error) {
	binaryJSON, err := json.Marshal(executable)
	if err != nil {
		return nil, fmt.Errorf("encode executable path: %w", err)
	}
	configJSON, err := json.Marshal(pushoverConfig)
	if err != nil {
		return nil, fmt.Errorf("encode config path: %w", err)
	}
	agentJSON, err := json.Marshal(agent)
	if err != nil {
		return nil, fmt.Errorf("encode agent name: %w", err)
	}
	declaration := "export const VibePushover = async"
	footer := ""
	if moduleDescriptor {
		declaration = "const VibePushover = async"
		footer = `

export default { id: "vibe-pushover", server: VibePushover };`
	}
	content := fmt.Sprintf(`%s
import { spawn } from "node:child_process";

const binary = %s;
const configPath = %s;

function notify(eventName, payload, directory) {
  const event = eventName === "session.idle"
    ? "turn-complete"
    : eventName === "session.error"
      ? "attention-required"
      : "approval-required";
  const args = ["notify", "--agent", %s, "--event", event, "--ignore-errors"];
  if (configPath) args.push("--config", configPath);
  const child = spawn(binary, args, { detached: true, stdio: ["pipe", "ignore", "inherit"] });
  child.on("error", (error) => console.error("[vibe-pushover] failed to start notifier:", error.message));
  child.stdin.on("error", (error) => console.error("[vibe-pushover] failed to send hook payload:", error.message));
  child.stdin.end(JSON.stringify({ cwd: directory, ...payload }));
  child.unref();
}

%s ({ directory }) => {
  const childSessions = new Set();
  const erroredSessions = new Set();

  return {
    event: async ({ event }) => {
      if (event.type === "session.created") {
        if (event.properties?.info?.parentID && event.properties.info.id) {
          childSessions.add(event.properties.info.id);
        }
      } else if (event.type === "session.deleted") {
        const deletedSessionID = event.properties?.info?.id ?? event.properties?.sessionID;
        if (deletedSessionID) {
          childSessions.delete(deletedSessionID);
          erroredSessions.delete(deletedSessionID);
        }
      } else if (event.type === "session.status") {
        if (event.properties?.status?.type !== "idle" && event.properties?.sessionID) {
          erroredSessions.delete(event.properties.sessionID);
        }
      } else if (event.type === "session.idle") {
        const sessionID = event.properties?.sessionID;
        if (sessionID && childSessions.has(sessionID)) return;
        if (sessionID && erroredSessions.delete(sessionID)) return;
        notify(event.type, event.properties ?? {}, directory);
      } else if (event.type === "permission.asked") {
        const properties = event.properties ?? {};
        notify(event.type, {
          ...properties,
          tool_name: properties.permission ?? properties.type ?? "Permission",
          message: properties.title ?? properties.message ?? "Approval requested.",
        }, directory);
      } else if (event.type === "session.error") {
        const properties = event.properties ?? {};
        const sessionID = properties.sessionID ?? properties.info?.id;
        if (sessionID && childSessions.has(sessionID)) return;
        if (sessionID) erroredSessions.add(sessionID);
        const error = properties.error;
        notify(event.type, {
          ...properties,
          message: typeof error === "string" ? error : error?.data?.message ?? error?.message ?? properties.message ?? "Agent turn failed.",
        }, directory);
      }
    },
  };
};%s
`, openCodePluginMarker, binaryJSON, configJSON, agentJSON, declaration, footer)
	return []byte(content), nil
}

func kiloPluginPath(goos, home string, getenv func(string) string) (string, error) {
	configDir := getenv("XDG_CONFIG_HOME")
	if configDir == "" && goos == "windows" {
		configDir = getenv("APPDATA")
		if configDir == "" {
			configDir = filepath.Join(home, "AppData", "Roaming")
		}
	}
	if configDir == "" {
		configDir = filepath.Join(home, ".config")
	} else if configDir == "~" || strings.HasPrefix(configDir, "~/") || strings.HasPrefix(configDir, `~\`) {
		if configDir == "~" {
			configDir = home
		} else {
			configDir = filepath.Join(home, configDir[2:])
		}
	}
	if !isAbsolutePathForOS(goos, configDir) {
		return "", fmt.Errorf("resolve Kilo Code config home: path must be absolute, got %q", configDir)
	}
	return filepath.Join(configDir, "kilo", "plugin", "vibe-pushover.ts"), nil
}

func writeGeneratedFile(path string, content []byte, pattern string) error {
	return writeGeneratedFileMode(path, content, pattern, 0o600)
}

func writeGeneratedFileMode(path string, content []byte, pattern string, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create plugin directory: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), pattern)
	if err != nil {
		return fmt.Errorf("create temporary plugin: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return fmt.Errorf("set plugin permissions: %w", err)
	}
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		return fmt.Errorf("write plugin: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close plugin: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replace plugin: %w", err)
	}
	return nil
}
