package hooks

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

const openCodePluginMarker = "// Generated by vibe-pushover."

func installOpenCodePlugin(path, executable, pushoverConfig string) (bool, error) {
	content, err := renderOpenCodePlugin(executable, pushoverConfig)
	if err != nil {
		return false, err
	}
	existing, err := os.ReadFile(path)
	if err == nil {
		if bytes.Equal(existing, content) {
			return false, nil
		}
		if !bytes.HasPrefix(existing, []byte(openCodePluginMarker)) {
			return false, fmt.Errorf("refusing to overwrite OpenCode plugin not owned by vibe-pushover: %s", path)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read OpenCode plugin: %w", err)
	}
	if err := writeGeneratedFile(path, content, ".vibe-pushover-*.ts"); err != nil {
		return false, err
	}
	return true, nil
}

func renderOpenCodePlugin(executable, pushoverConfig string) ([]byte, error) {
	binaryJSON, err := json.Marshal(executable)
	if err != nil {
		return nil, fmt.Errorf("encode executable path: %w", err)
	}
	configJSON, err := json.Marshal(pushoverConfig)
	if err != nil {
		return nil, fmt.Errorf("encode config path: %w", err)
	}
	content := fmt.Sprintf(`%s
import { spawn } from "node:child_process";

const binary = %s;
const configPath = %s;

function notify(eventName, payload, directory) {
  const event = eventName === "session.idle" ? "turn-complete" : "approval-required";
  const args = ["notify", "--agent", "opencode", "--event", event, "--ignore-errors"];
  if (configPath) args.push("--config", configPath);
  const child = spawn(binary, args, { detached: true, stdio: ["pipe", "ignore", "inherit"] });
  child.on("error", (error) => console.error("[vibe-pushover] failed to start notifier:", error.message));
  child.stdin.on("error", (error) => console.error("[vibe-pushover] failed to send hook payload:", error.message));
  child.stdin.end(JSON.stringify({ cwd: directory, ...payload }));
  child.unref();
}

export const VibePushover = async ({ directory }) => ({
  event: async ({ event }) => {
    if (event.type === "session.idle") {
      notify(event.type, event.properties ?? {}, directory);
    } else if (event.type === "permission.asked") {
      const properties = event.properties ?? {};
      notify(event.type, {
        ...properties,
        tool_name: properties.permission ?? properties.type ?? "Permission",
        message: properties.title ?? properties.message ?? "Approval requested.",
      }, directory);
    }
  },
});
`, openCodePluginMarker, binaryJSON, configJSON)
	return []byte(content), nil
}

func writeGeneratedFile(path string, content []byte, pattern string) error {
	return writeGeneratedFileMode(path, content, pattern, 0o600)
}

func writeGeneratedFileMode(path string, content []byte, pattern string, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create plugin directory: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), pattern)
	if err != nil {
		return fmt.Errorf("create temporary plugin: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return fmt.Errorf("set plugin permissions: %w", err)
	}
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		return fmt.Errorf("write plugin: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close plugin: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replace plugin: %w", err)
	}
	return nil
}
