package hooks

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

const openCodePluginMarker = "// Generated by vibe-pushover."

func installOpenCodePlugin(path, executable, pushoverConfig, agent, displayName string) (bool, error) {
	resolvedPath, err := resolveOpenCodePluginPath(path, displayName)
	if err != nil {
		return false, err
	}
	path = resolvedPath
	content, err := renderOpenCodePlugin(executable, pushoverConfig, agent)
	if err != nil {
		return false, err
	}
	existing, err := os.ReadFile(path)
	if err == nil {
		if bytes.Equal(existing, content) {
			return false, nil
		}
		if !bytes.HasPrefix(existing, []byte(openCodePluginMarker)) {
			return false, fmt.Errorf("refusing to overwrite %s plugin not owned by vibe-pushover: %s", displayName, path)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read %s plugin: %w", displayName, err)
	}
	if err := writeGeneratedFile(path, content, ".vibe-pushover-*.ts"); err != nil {
		return false, err
	}
	return true, nil
}

func resolveOpenCodePluginPath(path, displayName string) (string, error) {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return path, nil
	}
	if err != nil {
		return "", fmt.Errorf("inspect %s plugin: %w", displayName, err)
	}
	if info.Mode()&os.ModeSymlink == 0 {
		return path, nil
	}
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil {
		return "", fmt.Errorf("resolve %s plugin symlink: %w", displayName, err)
	}
	return resolved, nil
}

func renderOpenCodePlugin(executable, pushoverConfig, agent string) ([]byte, error) {
	binaryJSON, err := json.Marshal(executable)
	if err != nil {
		return nil, fmt.Errorf("encode executable path: %w", err)
	}
	configJSON, err := json.Marshal(pushoverConfig)
	if err != nil {
		return nil, fmt.Errorf("encode config path: %w", err)
	}
	agentJSON, err := json.Marshal(agent)
	if err != nil {
		return nil, fmt.Errorf("encode agent name: %w", err)
	}
	content := fmt.Sprintf(`%s
import { spawn } from "node:child_process";

const binary = %s;
const configPath = %s;

function notify(eventName, payload, directory) {
  const event = eventName === "session.idle" ? "turn-complete" : "approval-required";
  const args = ["notify", "--agent", %s, "--event", event, "--ignore-errors"];
  if (configPath) args.push("--config", configPath);
  const child = spawn(binary, args, { detached: true, stdio: ["pipe", "ignore", "inherit"] });
  child.on("error", (error) => console.error("[vibe-pushover] failed to start notifier:", error.message));
  child.stdin.on("error", (error) => console.error("[vibe-pushover] failed to send hook payload:", error.message));
  child.stdin.end(JSON.stringify({ cwd: directory, ...payload }));
  child.unref();
}

export const VibePushover = async ({ directory }) => {
  const childSessions = new Set();

  return {
    event: async ({ event }) => {
      if (event.type === "session.created") {
        if (event.properties?.info?.parentID && event.properties.info.id) {
          childSessions.add(event.properties.info.id);
        }
      } else if (event.type === "session.deleted") {
        const deletedSessionID = event.properties?.info?.id ?? event.properties?.sessionID;
        if (deletedSessionID) childSessions.delete(deletedSessionID);
      } else if (event.type === "session.idle") {
        const sessionID = event.properties?.sessionID;
        if (sessionID && childSessions.has(sessionID)) return;
        notify(event.type, event.properties ?? {}, directory);
      } else if (event.type === "permission.asked") {
        const properties = event.properties ?? {};
        notify(event.type, {
          ...properties,
          tool_name: properties.permission ?? properties.type ?? "Permission",
          message: properties.title ?? properties.message ?? "Approval requested.",
        }, directory);
      }
    },
  };
};
`, openCodePluginMarker, binaryJSON, configJSON, agentJSON)
	return []byte(content), nil
}

func writeGeneratedFile(path string, content []byte, pattern string) error {
	return writeGeneratedFileMode(path, content, pattern, 0o600)
}

func writeGeneratedFileMode(path string, content []byte, pattern string, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create plugin directory: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), pattern)
	if err != nil {
		return fmt.Errorf("create temporary plugin: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return fmt.Errorf("set plugin permissions: %w", err)
	}
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		return fmt.Errorf("write plugin: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close plugin: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replace plugin: %w", err)
	}
	return nil
}
