package hooks

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

const piExtensionMarker = "// Generated by vibe-pushover."

func installPiExtension(path, executable, pushoverConfig string) (bool, error) {
	content, err := renderPiExtension(executable, pushoverConfig)
	if err != nil {
		return false, err
	}

	existing, err := os.ReadFile(path)
	if err == nil {
		if bytes.Equal(existing, content) {
			return false, nil
		}
		if !bytes.HasPrefix(existing, []byte(piExtensionMarker)) {
			return false, fmt.Errorf("refusing to overwrite Pi extension not owned by vibe-pushover: %s", path)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read Pi extension: %w", err)
	}

	if err := writePiExtension(path, content); err != nil {
		return false, err
	}
	return true, nil
}

func renderPiExtension(executable, pushoverConfig string) ([]byte, error) {
	binaryJSON, err := json.Marshal(executable)
	if err != nil {
		return nil, fmt.Errorf("encode executable path: %w", err)
	}
	configJSON, err := json.Marshal(pushoverConfig)
	if err != nil {
		return nil, fmt.Errorf("encode config path: %w", err)
	}

	content := fmt.Sprintf(`%s
import { spawn } from "node:child_process";

const binary = %s;
const configPath = %s;
let lastAssistantMessage = "";

function assistantText(message) {
  if (!message || message.role !== "assistant") return "";
  if (typeof message.content === "string") return message.content;
  if (!Array.isArray(message.content)) return "";
  return message.content
    .filter((part) => part && part.type === "text" && typeof part.text === "string")
    .map((part) => part.text)
    .join("");
}

function sendTurnComplete(ctx) {
  const args = ["notify", "--agent", "pi", "--event", "turn-complete", "--ignore-errors"];
  if (configPath) args.push("--config", configPath);

  const child = spawn(binary, args, {
    detached: true,
    stdio: ["pipe", "ignore", "inherit"],
  });
  child.on("error", (error) => {
    console.error("[vibe-pushover] failed to start notifier:", error.message);
  });
  child.stdin.on("error", (error) => {
    console.error("[vibe-pushover] failed to send hook payload:", error.message);
  });
  child.stdin.end(JSON.stringify({
    cwd: ctx.cwd,
    last_assistant_message: lastAssistantMessage,
  }));
  child.unref();
}

export default function (pi) {
  pi.on("message_end", (event) => {
    const text = assistantText(event.message);
    if (text) lastAssistantMessage = text;
  });

  pi.on("agent_settled", (_event, ctx) => {
    sendTurnComplete(ctx);
    lastAssistantMessage = "";
  });
}
`, piExtensionMarker, binaryJSON, configJSON)
	return []byte(content), nil
}

func writePiExtension(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create Pi extension directory: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".vibe-pushover-*.ts")
	if err != nil {
		return fmt.Errorf("create temporary Pi extension: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return fmt.Errorf("set Pi extension permissions: %w", err)
	}
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		return fmt.Errorf("write Pi extension: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close Pi extension: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replace Pi extension: %w", err)
	}
	return nil
}
