package hooks

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

const tabnineHookMarker = "# Generated by vibe-pushover for Tabnine CLI."

type tabnineHookSpec struct {
	file  string
	event string
}

func installTabnineHooks(settingsPath, executable, pushoverConfig string) (bool, error) {
	if runtime.GOOS == "windows" {
		return false, errors.New("Tabnine CLI notification integration currently requires macOS or Linux")
	}
	writePath, err := resolveJSONHookPath(settingsPath, "Tabnine")
	if err != nil {
		return false, err
	}
	root, err := readRoot(writePath)
	if err != nil {
		return false, err
	}
	hookSettings, ok := root["hooks"].(map[string]any)
	if root["hooks"] != nil && !ok {
		return false, errors.New("Tabnine settings field \"hooks\" must be an object")
	}
	settingsChanged := false
	if !ok {
		hookSettings = map[string]any{}
		root["hooks"] = hookSettings
		settingsChanged = true
	}
	if enabled, exists := hookSettings["enabled"]; exists {
		if _, ok := enabled.(bool); !ok {
			return false, errors.New("Tabnine settings field \"hooks.enabled\" must be a boolean")
		}
	}
	if hookSettings["enabled"] != true {
		hookSettings["enabled"] = true
		settingsChanged = true
	}

	hooksDir := filepath.Join(filepath.Dir(filepath.Dir(settingsPath)), "hooks")
	type pendingScript struct {
		path    string
		content []byte
		changed bool
	}
	pending := make([]pendingScript, 0, 2)
	for _, spec := range []tabnineHookSpec{
		{file: "after-agent.sh", event: "turn-complete"},
		{file: "on-error.sh", event: "attention-required"},
	} {
		command, err := hookNotifyCommandForOSWithFlags(runtime.GOOS, "tabnine", "Tabnine", executable, spec.event, pushoverConfig, "--no-input")
		if err != nil {
			return false, err
		}
		content := []byte("#!/bin/sh\n" + tabnineHookMarker + "\n" + command + "\n")
		path := filepath.Join(hooksDir, spec.file)
		changed, err := tabnineHookScriptChanged(path, content)
		if err != nil {
			return false, err
		}
		pending = append(pending, pendingScript{path: path, content: content, changed: changed})
	}

	changed := settingsChanged
	for _, script := range pending {
		if !script.changed {
			continue
		}
		if err := writeGeneratedFileMode(script.path, script.content, ".vibe-pushover-tabnine-*", 0o700); err != nil {
			return false, err
		}
		changed = true
	}
	if settingsChanged {
		if err := writeJSON(writePath, root); err != nil {
			return false, err
		}
	}
	return changed, nil
}

func tabnineHookScriptChanged(path string, want []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return true, nil
	}
	if err != nil {
		return false, fmt.Errorf("read Tabnine hook script: %w", err)
	}
	if !bytes.HasPrefix(existing, []byte("#!/bin/sh\n"+tabnineHookMarker+"\n")) {
		return false, fmt.Errorf("refusing to overwrite Tabnine hook script not owned by vibe-pushover: %s", path)
	}
	info, err := os.Stat(path)
	if err != nil {
		return false, fmt.Errorf("stat Tabnine hook script: %w", err)
	}
	return !bytes.Equal(existing, want) || info.Mode().Perm()&0o100 == 0, nil
}
